//! Build script: generates the `include_str!` include-list for the embedded
//! model catalog snapshot (`assets/model-data/*.json`), mirroring upstream's
//! per-provider `import ... with { type: "json" }` over
//! `packages/ai/src/providers/data/*.json`.
//!
//! The generated module (`$OUT_DIR/model_data.rs`, never committed) declares:
//! - `MODEL_DATA_FILES: &[(&str, &str)]` — `(provider id, JSON text)`, sorted
//!   by provider id, one entry per provider data file;
//! - `MODEL_DATA_MANIFEST: &str` — the `.manifest.json` generation manifest
//!   (upstream imports it the same way in `providers/all.ts`).
//!
//! Embedded paths are absolute (`CARGO_MANIFEST_DIR`-anchored) because the
//! generated file lives under `target/`; it is regenerated per machine on
//! every build, so this stays portable.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const MANIFEST_FILE: &str = ".manifest.json";

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let data_dir = Path::new(&manifest_dir).join("assets").join("model-data");
    println!("cargo:rerun-if-changed={}", data_dir.display());

    let mut provider_ids: Vec<String> = fs::read_dir(&data_dir)
        .unwrap_or_else(|error| {
            panic!(
                "model data directory {} is unreadable: {error}",
                data_dir.display()
            )
        })
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| name.ends_with(".json") && name != MANIFEST_FILE)
        .map(|name| name[..name.len() - ".json".len()].to_string())
        .collect();
    provider_ids.sort();
    if provider_ids.is_empty() {
        panic!(
            "model data directory {} contains no provider data files",
            data_dir.display()
        );
    }

    // Directory mtime only notices additions/removals; watch every file so
    // content edits also rebuild the include-list.
    for id in &provider_ids {
        println!(
            "cargo:rerun-if-changed={}",
            data_dir.join(format!("{id}.json")).display()
        );
    }
    println!(
        "cargo:rerun-if-changed={}",
        data_dir.join(MANIFEST_FILE).display()
    );

    let base = data_dir.to_string_lossy().replace('\\', "/");
    let mut generated = String::new();
    generated.push_str("// Generated by build.rs from assets/model-data; do not edit.\n");
    generated.push_str(
        "\n/// Embedded provider data files: `(provider id, JSON text)`, sorted by provider id.\n",
    );
    generated.push_str("pub static MODEL_DATA_FILES: &[(&str, &str)] = &[\n");
    for id in &provider_ids {
        let _ = writeln!(
            generated,
            "    (\"{id}\", include_str!(\"{base}/{id}.json\")),"
        );
    }
    generated.push_str("];\n");
    generated.push_str("\n/// Embedded generation manifest (upstream `data/.manifest.json`).\n");
    let _ = writeln!(
        generated,
        "pub static MODEL_DATA_MANIFEST: &str = include_str!(\"{base}/{MANIFEST_FILE}\");"
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    fs::write(Path::new(&out_dir).join("model_data.rs"), generated)
        .expect("generated model data module must be writable");
}
