// Generates src/tui/terminal_image/oracle_consts.rs from oracle_output.json.
// Modeled on scratch/main_screen_oracle/gen_consts.mjs: canonical JSON
// (recursively key-sorted), one raw-string Rust const.
//
// Size trims applied here (the upstream-side oracle ran the FULL data; the
// Rust side rebuilds programmatic content and compares results):
// - isImageLine rows longer than 256 chars are stored as {long:true,result};
//   the Rust test rebuilds those exact lines (same construction order) and
//   compares the boolean result by index.
// - registryFlow placement transmissionGeneration values are normalized
//   relative to the first generation inside the flow, because the Rust replay
//   runs against a fresh registry while the oracle process had accumulated
//   global registrations before the flow.
import fs from "node:fs";

const o = JSON.parse(fs.readFileSync(new URL("./oracle_output.json", import.meta.url), "utf8"));

// normalize: subtract base generation so a fresh-registry replay matches
let firstGen;
for (const row of o.registryFlow) {
	if (row.op === "placement" && row.placement) {
		firstGen = firstGen === undefined ? row.placement.transmissionGeneration : Math.min(firstGen, row.placement.transmissionGeneration);
	}
}
const registryFlow = o.registryFlow.map((row) => {
	if (row.op === "placement" && row.placement && firstGen > 1) {
		return { ...row, placement: { ...row.placement, transmissionGeneration: row.placement.transmissionGeneration - (firstGen - 1) } };
	}
	return row;
});

const isImageLine = o.isImageLine.map((row) =>
	row.line.length > 256 ? { long: true, result: row.result } : { line: row.line, result: row.result },
);

const canonicalJson = JSON.stringify({
	meta: o.meta,
	base64Decode: o.base64Decode,
	base64ByteLength: o.base64ByteLength,
	detect: o.detect,
	overrideFlow: o.overrideFlow,
	encodeKitty: o.encodeKitty,
	deleteCommands: o.deleteCommands,
	encodeITerm2: o.encodeITerm2,
	cellSize: o.cellSize,
	calculateRows: o.calculateRows,
	registryFlow,
	dimensions: o.dimensions,
	renderCases: o.renderCases,
	renderMetadataAfter: o.renderMetadataAfter,
	fallbackHome: o.fallbackHome,
	fallback: o.fallback,
	hyperlink: o.hyperlink,
	isImageLine,
	allocateImageId: o.allocateImageId,
});
if (canonicalJson.includes('"##')) throw new Error("canonical JSON contains raw-string terminator");

const rust = `// Generated by scratch/terminal_image_oracle/gen_consts.mjs from
// oracle_output.json — do not edit by hand. Every value was captured by
// running the actual upstream terminal-image.ts (sha256
// ${o.meta.upstreamSha256}) under node ${o.meta.node} on ${o.meta.platform}.
// Long isImageLine rows are stored as {"long":true,"result":...}; the test
// rebuilds those programmatic lines and compares the boolean by index.
#![allow(dead_code)]

pub(crate) const ORACLE_JSON: &str = r##"${canonicalJson}"##;
`;

const target = new URL("../../src/tui/terminal_image/oracle_consts.rs", import.meta.url);
fs.writeFileSync(target, rust);
console.log(
	"wrote oracle_consts.rs:",
	canonicalJson.length,
	"bytes json;",
	"flow firstGen:",
	firstGen,
	"long line rows:",
	isImageLine.filter((r) => r.long).length,
);
