// Generated by tests/fixtures/main_screen_oracle/gen_consts.mjs from oracle_output.json — do not edit by hand.
// Every value was captured by running the actual upstream tui-main-screen.ts
// (TuiMainScreen over the real TuiBase) under node --experimental-strip-types;
// byte arrays are FakeTerminal write boundaries (one entry per terminal.write call).

pub const SPINNER_FRAME_0_WRITES: &[&str] = &["\u{1b}[?2026hHeader\u{1b}[0m\u{1b}]8;;\u{7}\r\nWorking |\u{1b}[0m\u{1b}]8;;\u{7}\r\nFooter\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const SPINNER_FRAME_1_WRITES: &[&str] = &[
    "\u{1b}[?2026h\u{1b}[1A\r\u{1b}[2KWorking /\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l",
    "\u{1b}[?25l",
];
pub const SPINNER_FRAME_2_WRITES: &[&str] = &[
    "\u{1b}[?2026h\r\u{1b}[2KWorking -\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l",
    "\u{1b}[?25l",
];
pub const SPINNER_FRAME_3_WRITES: &[&str] = &[
    "\u{1b}[?2026h\r\u{1b}[2KWorking \\\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l",
    "\u{1b}[?25l",
];
pub const NO_CHANGE_WRITES: &[&str] = &["\u{1b}[?25l"];
pub const FIRST_RENDER_WRITES: &[&str] = &["\u{1b}[?25l", "\u{1b}[?2026hLine 0\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 1\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 2\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const FIRST_RENDER_FULL_REDRAWS: usize = 1;
pub const STOP_DEFAULT_WRITES: &[&str] = &[" ", "\u{1b}[1B", "\r\n", "\u{1b}[?25h"];
pub const RENDER_AFTER_STOP_WRITES: &[&str] = &[];
pub const STOP_PRESERVE_SCREEN_WRITES: &[&str] = &["\u{1b}[?25h"];
pub const NONADJACENT_CHANGE_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[3A\r\u{1b}[2KCHANGED 1\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[2KLine 2\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[2KCHANGED 3\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const APPEND_LINES_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[1B\r\n\u{1b}[2KLine 5\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[2KLine 6\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const DELETE_TAIL_LINES_WRITES: &[&str] = &[
    "\u{1b}[?2026h\u{1b}[2A\r\u{1b}[1B\r\u{1b}[2K\u{1b}[1B\r\u{1b}[2K\u{1b}[2A\u{1b}[?2026l",
    "\u{1b}[?25l",
];
pub const SHRINK_THEN_CHANGE_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[3A\r\u{1b}[2KCHANGED\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[2KLine 2\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[2K\r\n\u{1b}[2K\u{1b}[2A\u{1b}[?2026l", "\u{1b}[?25l"];
pub const FIRST_LINE_CHANGE_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2A\r\u{1b}[2KCHANGED\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[2KLine 1\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const APPEND_AFTER_CHANGE_WRITES: &[&str] = &[
    "\u{1b}[?2026h\u{1b}[1B\r\n\u{1b}[2KLine 3\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l",
    "\u{1b}[?25l",
];
pub const LAST_LINE_CHANGE_WRITES: &[&str] = &[
    "\u{1b}[?2026h\r\u{1b}[2KFINAL\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l",
    "\u{1b}[?25l",
];
pub const SHRINK_TO_EMPTY_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[3A\r\r\u{1b}[2K\u{1b}[1B\r\u{1b}[2K\u{1b}[1B\r\u{1b}[2K\u{1b}[1B\r\u{1b}[2K\u{1b}[3A\u{1b}[?2026l", "\u{1b}[?25l"];
pub const REGROW_AFTER_EMPTY_WRITES: &[&str] = &["\u{1b}[?2026hNew Line 0\u{1b}[0m\u{1b}]8;;\u{7}\r\nNew Line 1\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const CLEAR_ON_SHRINK_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3JLine 0\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 1\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const CLEAR_ON_SHRINK_DELTA: usize = 1;
pub const CLEAR_ON_SHRINK_SINGLE_WRITES: &[&str] = &[
    "\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3JOnly line\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l",
    "\u{1b}[?25l",
];
pub const CLEAR_ON_SHRINK_EMPTY_WRITES: &[&str] = &[
    "\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3J\u{1b}[?2026l",
    "\u{1b}[?25l",
];
pub const CLEAR_CHILDREN_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2A\r\r\u{1b}[2K\u{1b}[1B\r\u{1b}[2K\u{1b}[1B\r\u{1b}[2K\u{1b}[2A\u{1b}[?2026l", "\u{1b}[?25l"];
pub const DELETED_VIEWPORT_UP_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3JLine 0\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 1\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 2\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 3\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 4\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 5\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 6\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const DELETED_VIEWPORT_UP_DELTA: usize = 1;
pub const APPEND_AFTER_VIEWPORT_RESET_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[4A\r\u{1b}[1B\r\u{1b}[2K\u{1b}[1B\r\u{1b}[2K\u{1b}[1B\r\u{1b}[2K\u{1b}[1B\r\u{1b}[2K\u{1b}[4A\u{1b}[?2026l", "\u{1b}[?25l"];
pub const APPEND_AFTER_VIEWPORT_RESET_DELTA: usize = 0;
pub const TRANSIENT_INFLATION_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3JChat 0\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 1\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 2\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 3\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 4\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 5\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 6\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 7\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 8\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 9\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 10\u{1b}[0m\u{1b}]8;;\u{7}\r\nChat 11\u{1b}[0m\u{1b}]8;;\u{7}\r\nEditor 0\u{1b}[0m\u{1b}]8;;\u{7}\r\nEditor 1\u{1b}[0m\u{1b}]8;;\u{7}\r\nEditor 2\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const TRANSIENT_INFLATION_DELTA: usize = 1;
pub const RESIZE_WIDTH_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3JLine 0\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 1\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 2\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const RESIZE_WIDTH_DELTA: usize = 1;
pub const RESIZE_HEIGHT_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3JLine 0\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 1\u{1b}[0m\u{1b}]8;;\u{7}\r\nLine 2\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const RESIZE_HEIGHT_DELTA: usize = 1;
pub const TERMUX_RESIZE_FRAME_0_WRITES: &[&str] = &["\u{1b}[?25l"];
pub const TERMUX_RESIZE_FRAME_1_WRITES: &[&str] = &["\u{1b}[?25l"];
pub const TERMUX_RESIZE_FRAME_2_WRITES: &[&str] = &["\u{1b}[?25l"];
pub const TERMUX_RESIZE_FRAME_3_WRITES: &[&str] = &["\u{1b}[?25l"];
pub const TERMUX_RESIZE_DELTA: usize = 0;
pub const CURSOR_MARKER_MOVED_WRITES: &[&str] = &["\u{1b}[1B\u{1b}[5G", "\u{1b}[?25l"];
pub const CURSOR_MARKER_VISIBLE_WRITES: &[&str] = &["\u{1b}[1B\u{1b}[5G", "\u{1b}[?25h"];
pub const STYLES_RESET_WRITES: &[&str] = &["\u{1b}[?25l", "\u{1b}[?2026h\u{1b}[3mItalic\u{1b}[0m\u{1b}]8;;\u{7}\r\nPlain\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const KEYBOARD_PREEMPT: &str = "{\"lines\":[\"typed\"],\"renderCountDelta\":1}";
pub const BOUNDED_FULL: &str = "{\"fullRedraws\":1,\"head\":\"\\u001b[?2026h\\u001b_Ga=T,f=100;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\",\"joinedLength\":2400054,\"joinedSha256\":\"2f6374e4e16d3a7eed173b16039396c70538e021917306601cef1f7ca2137f52\",\"tail\":\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\u001b\\\\\\u001b[?2026l\\u001b[?25l\",\"writeCount\":4,\"writeLengths\":[1048576,1048576,302896,6]}";
pub const BOUNDED_DIFF: &str = "{\"endsWithSync\":false,\"hasFullClear\":false,\"head\":\"\\u001b[?2026h\\r\\n\\u001b[2K\\u001b_Ga=T,f=100;AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\",\"joinedLength\":2400064,\"joinedSha256\":\"ac197f8d54cd3dbd9da6d444847979d16ad4d24fa01f228f8745a27075ad795f\",\"startsWithSync\":true,\"tail\":\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\u001b\\\\\\u001b[?2026l\\u001b[?25l\",\"writeCount\":4,\"writeLengths\":[1048576,1048576,302906,6]}";
pub const KITTY_RESERVED_ROWS_DIFF_WRITES: &[&str] = &["\u{1b}[?2026h\r\n\u{1b}[2K\r\n\u{1b}[2K\u{1b}[1A\u{1b}_Ga=T,f=100,q=2,C=1,c=2,r=2,i=42;AAAA\u{1b}\\\u{1b}[1B\r\n\u{1b}[2Kafter\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const KITTY_PRECLEAR_SCROLL_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3Jbefore\u{1b}[0m\u{1b}]8;;\u{7}\r\n\r\n\u{1b}[1A\u{1b}_Ga=T,f=100,q=2,C=1,c=2,r=2,i=42;AAAA\u{1b}\\\u{1b}[1B\r\nafter\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const KITTY_PRECLEAR_SCROLL_DELTA: usize = 1;
pub const KITTY_FULLREDRAW_RESERVED_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3Jl0\u{1b}[0m\u{1b}]8;;\u{7}\r\nl1\u{1b}[0m\u{1b}]8;;\u{7}\r\nl2\u{1b}[0m\u{1b}]8;;\u{7}\r\nl3\u{1b}[0m\u{1b}]8;;\u{7}\r\nl4\u{1b}[0m\u{1b}]8;;\u{7}\r\n\r\n\r\n\u{1b}[2A\u{1b}_Ga=T,f=100,q=2,C=1,c=3,r=3,i=55;AAAA\u{1b}\\\u{1b}[2B\r\nafter\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const KITTY_FULLREDRAW_RESERVED_DELTA: usize = 1;
pub const KITTY_TALLER_THAN_VIEWPORT_WRITES: &[&str] = &["\u{1b}[?2026h\u{1b}[2J\u{1b}[H\u{1b}[3Jbefore\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}_Ga=T,f=100,q=2,C=1,c=6,r=6,i=66;AAAA\u{1b}\\\r\n\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[0m\u{1b}]8;;\u{7}\r\nafter\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l", "\u{1b}[?25l"];
pub const KITTY_TALLER_HAS_CURSOR_UP_PREFIX: &str = "{\"value\":false}";
pub const KITTY_DELETE_CHANGED_JOINED: &str = "\u{1b}[?2026h\u{1b}_Ga=d,d=I,i=42,q=2\u{1b}\\\u{1b}[1A\r\u{1b}[2K\u{1b}_Ga=T,f=100,q=2,C=1,c=2,r=1,i=42;BBBB\u{1b}\\\r\n\u{1b}[2K\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l\u{1b}[?25l";
pub const KITTY_DELETE_CHANGED_META: &str =
    "{\"deleteBeforeDraw\":true,\"deleteIndex\":8,\"drawIndex\":38}";
pub const KITTY_RESERVED_ROW_CHANGE_JOINED: &str = "\u{1b}[?2026h\u{1b}_Ga=d,d=I,i=88,q=2\u{1b}\\\u{1b}[1A\r\u{1b}[2Kcovered\u{1b}[0m\u{1b}]8;;\u{7}\r\n\u{1b}[2K\u{1b}_Ga=T,f=100,q=2,C=1,c=2,r=2,i=88;AAAA\u{1b}\\\u{1b}[?2026l\u{1b}[?25l";
pub const KITTY_RESERVED_ROW_CHANGE_META: &str =
    "{\"deleteBeforeDraw\":true,\"deleteIndex\":8,\"drawIndex\":61,\"hasFullClear\":false}";
pub const KITTY_FULLREDRAW_DELETES_PREVIOUS_JOINED: &str = "\u{1b}[?2026h\u{1b}_Ga=d,d=I,i=77,q=2\u{1b}\\\u{1b}[2J\u{1b}[H\u{1b}[3Jplain text\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l\u{1b}[?25l";
pub const KITTY_FULLREDRAW_DELETES_PREVIOUS_META: &str =
    "{\"clearIndex\":29,\"deleteBeforeClear\":true,\"deleteIndex\":8}";
pub const CRASH_DUMP_LOGDIR_MESSAGE: &str = "Rendered line 1 exceeds terminal width (60 > 40).\n\nThis is likely caused by a custom TUI component not truncating its output.\nUse visibleWidth() to measure and truncateToWidth() to truncate lines.\n\nDebug log written to: <LOG_DIR>\\pi-tui-crash.log";
pub const CRASH_DUMP_LOGDIR_TEXT: &str = "Crash at <TS>\nTerminal width: 40\nLine 1 visible width: 60\n\n=== All rendered lines ===\n[0] (w=2) ok\u{1b}[0m\u{1b}]8;;\u{7}\n[1] (w=60) xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\u{1b}[0m\u{1b}]8;;\u{7}\n";
pub const CRASH_DUMP_LOGDIR_STOP_WRITES: &[&str] = &[" ", "\u{1b}[1B", "\r\n", "\u{1b}[?25h"];
pub const CRASH_DUMP_TMPDIR_MESSAGE: &str = "Rendered line 1 exceeds terminal width (60 > 40).\n\nThis is likely caused by a custom TUI component not truncating its output.\nUse visibleWidth() to measure and truncateToWidth() to truncate lines.\n\nDebug log written to: <CRASH_DIR>\\pi-tui-crash.log";
pub const CRASH_DUMP_TMPDIR_TEXT: &str = "Crash at <TS>\nTerminal width: 40\nLine 1 visible width: 60\n\n=== All rendered lines ===\n[0] (w=2) ok\u{1b}[0m\u{1b}]8;;\u{7}\n[1] (w=60) xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\u{1b}[0m\u{1b}]8;;\u{7}\n";
pub const DEBUG_REDRAW_LOG_TEXT: &str = "[<TS>] fullRender: first render (prev=0, new=3, height=10)\n[<TS>] fullRender: terminal width changed (40 -> 60) (prev=3, new=3, height=10)\n[<TS>] fullRender: clearOnShrink (maxLinesRendered=3) (prev=3, new=1, height=10)\n";
pub const PI_TUI_DEBUG_DUMP_CONTENT: &str = "firstChanged: 1\nviewportTop: 0\ncursorRow: 2\nheight: 10\nlineDiff: -1\nhardwareCursorRow: 2\nrenderEnd: 1\nfinalCursorRow: 1\ncursorPos: null\nnewLines.length: 3\npreviousLines.length: 3\n\n=== newLines ===\n[\n  \"Header\\u001b[0m\\u001b]8;;\\u0007\",\n  \"Working /\\u001b[0m\\u001b]8;;\\u0007\",\n  \"Footer\\u001b[0m\\u001b]8;;\\u0007\"\n]\n\n=== previousLines ===\n[\n  \"Header\\u001b[0m\\u001b]8;;\\u0007\",\n  \"Working |\\u001b[0m\\u001b]8;;\\u0007\",\n  \"Footer\\u001b[0m\\u001b]8;;\\u0007\"\n]\n\n=== buffer ===\n[44 chars written in bounded chunks]";
pub const RESTORE_RENDER_STATE_WRITES: &[&str] = &["\u{1b}[?25l"];
pub const RESTORE_RENDER_STATE_IMAGES_WRITES: &[&str] = &[
    "\u{1b}[?2026h\u{1b}[1A\r\u{1b}[2Kchanged\u{1b}[0m\u{1b}]8;;\u{7}\u{1b}[?2026l",
    "\u{1b}[?25l",
];
pub const RENDER_STATE_SHAPE: &str = "{\"cursorRow\":1,\"hardwareCursorRow\":1,\"maxLinesRendered\":2,\"mode\":\"regular\",\"previousHeight\":10,\"previousLinesLength\":2,\"previousViewportTop\":0,\"previousWidth\":40}";
