//! Byte-oracle tests for the ai-delta slice: every expectation here was
//! captured by EXECUTING the actual upstream TypeScript (2bbfcca43) under
//! Node `--experimental-strip-types` — see
//! `tests/fixtures/ai_delta_oracle/capture_ai_delta.mjs` (the generator, kept
//! with the fixture) and `ai_delta_oracle.manifest.json` (the SHA-256
//! provenance of every captured source).
//!
//! Comparisons over JSON objects are canonical (serde_json `Value` equality,
//! which sorts object keys): the port's `BTreeMap` carrier cannot reproduce
//! JS insertion order; the pinned contract is the key SET and every value,
//! plus the exact request method/header values and body shape.

use serde_json::Value;

/// The captured fixture (generated by the committed capture script against
/// upstream 2bbfcca43).
fn oracle() -> Value {
    serde_json::from_str(include_str!(
        "../../../tests/fixtures/ai_delta_oracle/ai_delta_oracle.json"
    ))
    .expect("oracle fixture must parse")
}

// ---------------------------------------------------------------------------
// 1. llama-cpp-classify pure functions
// ---------------------------------------------------------------------------
#[cfg(test)]
mod llama_cpp {
    use super::*;
    use crate::ai::api::llama_cpp_classify::{
        answer_from_probabilities, label_probabilities, llama_server_root, peak_confidence,
        render_question,
    };
    use crate::ai::types::classifier::{
        ClassifierBoolCriteria, ClassifierChoiceQuestion, ClassifierContext, ClassifierQuestion,
        ClassifierScoreQuestion,
    };
    use crate::ai::types::ordered_map::OrderedMap;

    fn oracle_context() -> ClassifierContext {
        ClassifierContext {
            state: serde_json::json!({"alpha": 1, "beta": [true, false], "gamma": {"deep": "x"}}),
            questions: OrderedMap::from_pairs([
                (
                    "choice1".to_string(),
                    ClassifierQuestion::Choice(ClassifierChoiceQuestion {
                        instructions: "Pick the best option.".into(),
                        criteria: OrderedMap::from_pairs([
                            ("cost".to_string(), "Cheap".to_string()),
                            ("quality".to_string(), "Accurate".to_string()),
                            ("speed".to_string(), "Fast".to_string()),
                        ]),
                    }),
                ),
                (
                    "score1".to_string(),
                    ClassifierQuestion::Score(ClassifierScoreQuestion {
                        instructions: "Rate the reply.".into(),
                        criteria: vec!["Bad".into(), "OK".into(), "Great".into()],
                    }),
                ),
                (
                    "bool1".to_string(),
                    ClassifierQuestion::Bool(
                        crate::ai::types::classifier::ClassifierBoolQuestion {
                            instructions: "Is the state positive?".into(),
                            criteria: ClassifierBoolCriteria {
                                r#true: "Yes it is".into(),
                                r#false: "No it is not".into(),
                            },
                        },
                    ),
                ),
            ]),
        }
    }

    #[test]
    fn llama_server_root_matches_upstream() {
        let fixture = &oracle()["llamaCpp"];
        let expected: Vec<String> = fixture["llamaServerRoot"]
            .as_array()
            .unwrap()
            .iter()
            .map(|value| value.as_str().unwrap().to_string())
            .collect();
        let actual: Vec<String> = [
            "https://api.example.com/v1",
            "https://api.example.com/v1/",
            "https://api.example.com",
            "http://localhost:8080/v1/",
        ]
        .iter()
        .map(|url| llama_server_root(url))
        .collect();
        assert_eq!(actual, expected);
    }

    /// The rendered user message content and the label/key lists are pinned
    /// byte-for-byte (the content embeds the 1-space `JSON.stringify(state)`,
    /// which the port reproduces with the re-indent helper).
    #[test]
    fn render_question_matches_upstream_bytes() {
        let fixture = &oracle()["llamaCpp"]["renderQuestion"];
        let context = oracle_context();
        for id in ["choice1", "score1", "bool1"] {
            let rendered = render_question(&context, id).unwrap();
            let upstream = &fixture[id];
            assert_eq!(
                rendered.content,
                upstream["content"].as_str().unwrap(),
                "{id}"
            );
            let labels: Vec<String> = upstream["labels"]
                .as_array()
                .unwrap()
                .iter()
                .map(|value| value.as_str().unwrap().to_string())
                .collect();
            let keys: Vec<String> = upstream["keys"]
                .as_array()
                .unwrap()
                .iter()
                .map(|value| value.as_str().unwrap().to_string())
                .collect();
            assert_eq!(rendered.labels, labels, "{id}");
            assert_eq!(rendered.keys, keys, "{id}");
        }
    }

    #[test]
    fn label_probabilities_match_upstream() {
        let fixture = &oracle()["llamaCpp"]["labelProbabilities"];
        let actual = [
            label_probabilities(&[0.1, 0.4, 0.9], 1.0),
            label_probabilities(&[0.1, 0.4, 0.9], 2.0),
            label_probabilities(&[-1e30, -2.0, -2.0], 1.0),
        ];
        for (actual, expected) in actual.iter().zip(fixture.as_array().unwrap()) {
            let expected: Vec<f64> = expected
                .as_array()
                .unwrap()
                .iter()
                .map(|value| value.as_f64().unwrap())
                .collect();
            for (a, e) in actual.iter().zip(&expected) {
                assert!((a - e).abs() < 1e-15, "{a} vs {e}");
            }
        }
    }

    #[test]
    fn peak_confidence_matches_upstream() {
        let fixture = &oracle()["llamaCpp"]["peakConfidence"];
        let actual = [
            peak_confidence(&[0.5, 0.5]),
            peak_confidence(&[1.0, 0.0, 0.0]),
            peak_confidence(&[0.4, 0.4, 0.2]),
        ];
        for (a, e) in actual.iter().zip(fixture.as_array().unwrap()) {
            let e = e.as_f64().unwrap();
            assert!((a - e).abs() < 1e-15, "{a} vs {e}");
        }
    }

    #[test]
    fn answer_from_probabilities_matches_upstream() {
        let fixture = &oracle()["llamaCpp"]["answerFromProbabilities"];
        let context = oracle_context();
        let cases = [
            ("choice1", vec![0.6, 0.3, 0.1], &fixture[0]),
            ("score1", vec![0.1, 0.2, 0.7], &fixture[1]),
            ("bool1", vec![0.9, 0.1], &fixture[2]),
        ];
        for (id, probabilities, expected) in cases {
            let question = context.questions.get(id).unwrap();
            let rendered = render_question(&context, id).unwrap();
            let answer = answer_from_probabilities(question, &rendered.keys, &probabilities);
            let wire = serde_json::to_value(&answer).unwrap();
            assert_eq!(wire, *expected, "{id}");
        }
    }

    #[test]
    fn render_question_error_messages_match_upstream() {
        let fixture = &oracle()["llamaCpp"]["renderQuestionErrors"];
        let one_choice = ClassifierContext {
            state: serde_json::json!({}),
            questions: OrderedMap::from_pairs([(
                "x".to_string(),
                ClassifierQuestion::Choice(ClassifierChoiceQuestion {
                    instructions: "i".into(),
                    criteria: OrderedMap::from_pairs([("a".to_string(), "1".to_string())]),
                }),
            )]),
        };
        let one_score = ClassifierContext {
            state: serde_json::json!({}),
            questions: OrderedMap::from_pairs([(
                "x".to_string(),
                ClassifierQuestion::Score(ClassifierScoreQuestion {
                    instructions: "i".into(),
                    criteria: vec!["a".into()],
                }),
            )]),
        };
        assert_eq!(
            render_question(&one_choice, "x").unwrap_err(),
            fixture[0].as_str().unwrap()
        );
        assert_eq!(
            render_question(&one_score, "x").unwrap_err(),
            fixture[1].as_str().unwrap()
        );
        assert_eq!(
            render_question(&ClassifierContext::default(), "missing").unwrap_err(),
            fixture[2].as_str().unwrap()
        );
    }
}

// ---------------------------------------------------------------------------
// 2. system-one classify over wiremock (the upstream capture injected fetch;
//    the port goes over real loopback HTTP — the same request shape/bytes)
// ---------------------------------------------------------------------------
#[cfg(test)]
mod system_one {
    use super::*;
    use crate::ai::api::cloudflare_workers_ai_system_one::classify as classify_cloudflare;
    use crate::ai::api::typesafe_system_one::classify as classify_typesafe;
    use crate::ai::types::classifier::{
        ClassifierBoolCriteria, ClassifierBoolQuestion, ClassifierChoiceQuestion,
        ClassifierContext, ClassifierOptions, ClassifierQuestion, ClassifierScoreQuestion,
        ClassifierStopReason,
    };
    use crate::ai::types::model::ClassifierModel;
    use crate::ai::types::model::{ModelInput, ModelType};
    use crate::ai::types::ordered_map::OrderedMap;
    use crate::ai::types::primitives::ModelCost;
    use wiremock::matchers::{method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    fn fixture() -> Value {
        oracle()["systemOne"].clone()
    }

    fn typesafe_model(base_url: &str) -> ClassifierModel {
        ClassifierModel {
            id: "jev-1".into(),
            name: "Jev 1".into(),
            api: "typesafe-system-one".into(),
            provider: "typesafe".into(),
            base_url: base_url.to_string(),
            input: vec![ModelInput::Text],
            input_limits: None,
            cost: ModelCost {
                input: 2.0,
                output: 8.0,
                cache_read: 0.2,
                cache_write: 0.4,
                tiers: None,
            },
            headers: None,
            r#type: ModelType::Classifier,
            context_window: 128000,
        }
    }

    fn cloudflare_model(base_url: &str) -> ClassifierModel {
        ClassifierModel {
            id: "jev-cf".into(),
            api: "cloudflare-workers-ai-system-one".into(),
            provider: "cloudflare-workers-ai".into(),
            base_url: base_url.to_string(),
            ..typesafe_model(base_url)
        }
    }

    fn oracle_context() -> ClassifierContext {
        ClassifierContext {
            state: serde_json::json!({"channel": "support", "turns": 3}),
            questions: OrderedMap::from_pairs([
                (
                    "q1".to_string(),
                    ClassifierQuestion::Choice(ClassifierChoiceQuestion {
                        instructions: "Tone?".into(),
                        criteria: OrderedMap::from_pairs([
                            ("polite".into(), "Kind".into()),
                            ("rude".into(), "Harsh".into()),
                        ]),
                    }),
                ),
                (
                    "q2".to_string(),
                    ClassifierQuestion::Score(ClassifierScoreQuestion {
                        instructions: "Quality?".into(),
                        criteria: vec!["Low".into(), "High".into()],
                    }),
                ),
                (
                    "q3".to_string(),
                    ClassifierQuestion::Bool(ClassifierBoolQuestion {
                        instructions: "Resolved?".into(),
                        criteria: ClassifierBoolCriteria {
                            r#true: "Yes".into(),
                            r#false: "No".into(),
                        },
                    }),
                ),
            ]),
        }
    }

    fn options() -> ClassifierOptions {
        ClassifierOptions {
            api_key: Some("sk-test".into()),
            max_retries: Some(0),
            ..Default::default()
        }
    }

    #[tokio::test]
    async fn typesafe_happy_path_matches_upstream_capture() {
        let server = MockServer::start().await;
        let response = &fixture()["typesafe"];
        // The canned SERVER body from the capture (wire-level noul answers).
        let canned = response["canned"].clone();
        Mock::given(method("POST"))
            .and(path("/systemone"))
            .respond_with(ResponseTemplate::new(200).set_body_json(canned))
            .expect(1)
            .mount(&server)
            .await;

        let model = typesafe_model(&format!("{}/", server.uri()));
        let result = classify_typesafe(&model, &oracle_context(), Some(&options())).await;

        // Request shape: method, path, and every captured header value.
        let captured = &response["requests"][0];
        assert_eq!(captured["method"].as_str().unwrap(), "POST");
        assert!(captured["url"].as_str().unwrap().ends_with("/systemone"));
        let requests = server.received_requests().await.unwrap();
        let sent = requests.last().unwrap();
        for (name, value) in captured["headers"].as_object().unwrap() {
            let wire = sent.headers.get(name).and_then(|value| value.to_str().ok());
            assert_eq!(wire, Some(value.as_str().unwrap()), "header {name}");
        }
        // Body: key-set/value equality against the captured wire bytes (the
        // port's BTreeMap carrier serializes sorted keys; the fixture's keys
        // are already sorted, so the parsed objects are equal).
        let body: Value = serde_json::from_slice(&sent.body).unwrap();
        let expected_body: Value =
            serde_json::from_str(captured["body"].as_str().unwrap()).unwrap();
        assert_eq!(body, expected_body);

        // Result: answers and catalog-priced usage match the capture.
        assert_eq!(
            result.stop_reason,
            ClassifierStopReason::Stop,
            "err: {:?}",
            result.error_message
        );
        assert!(result.error_message.is_none());
        let answers = serde_json::to_value(result.answers).unwrap();
        assert_eq!(answers, response["result"]["answers"]);
        let usage = serde_json::to_value(result.usage).unwrap();
        assert_eq!(usage["input"], response["result"]["usage"]["input"]);
        assert_eq!(usage["output"], response["result"]["usage"]["output"]);
        assert_eq!(
            usage["totalTokens"],
            response["result"]["usage"]["totalTokens"]
        );
        for bucket in ["input", "output", "cacheRead", "cacheWrite", "total"] {
            let actual = usage["cost"][bucket].as_f64().unwrap();
            let expected = response["result"]["usage"]["cost"][bucket]
                .as_f64()
                .unwrap();
            assert!(
                (actual - expected).abs() < 1e-15,
                "cost.{bucket}: {actual} vs {expected}"
            );
        }
    }

    #[tokio::test]
    async fn cloudflare_happy_path_matches_upstream_capture() {
        let server = MockServer::start().await;
        let response = &fixture()["cloudflare"];
        let canned = response["canned"].clone();
        Mock::given(method("POST"))
            .and(path("/ai/run"))
            .respond_with(ResponseTemplate::new(200).set_body_json(canned))
            .expect(1)
            .mount(&server)
            .await;

        let model = cloudflare_model(&format!("{}/ai", server.uri()));
        let result = classify_cloudflare(&model, &oracle_context(), Some(&options())).await;

        assert_eq!(
            result.stop_reason,
            ClassifierStopReason::Stop,
            "err: {:?}",
            result.error_message
        );
        assert!(result.error_message.is_none());
        let answers = serde_json::to_value(result.answers).unwrap();
        assert_eq!(answers, response["result"]["answers"]);
        // Usage priced from the catalog: 0 input, 12 output tokens.
        let usage = serde_json::to_value(result.usage).unwrap();
        assert_eq!(usage["input"], 0);
        assert_eq!(usage["output"], 12);
        assert!(usage["cost"]["output"].as_f64().unwrap() > 0.0);
    }

    /// The four captured error paths, replayed verbatim: exact upstream
    /// error-message strings and the error stop reason.
    #[tokio::test]
    async fn exact_upstream_error_messages_replay() {
        // (1) typesafe-error: HTTP 503 body composes
        // "{label} error ({status}): {body}" (formatProviderError on the
        // normalized HTTP error).
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .respond_with(ResponseTemplate::new(503).set_body_string("{\"error\":\"boom\"}"))
            .expect(1)
            .mount(&server)
            .await;
        let model = typesafe_model(&format!("{}/", server.uri()));
        let result = classify_typesafe(&model, &oracle_context(), Some(&options())).await;
        assert_eq!(result.stop_reason, ClassifierStopReason::Error);
        assert_eq!(
            result.error_message.as_deref(),
            Some("System One API error (503): {\"error\":\"boom\"}")
        );

        // (2) cloudflare-not-complete
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .respond_with(ResponseTemplate::new(200).set_body_json(
                serde_json::json!({"success": true, "result": {"state": "Running"}}),
            ))
            .expect(1)
            .mount(&server)
            .await;
        let model = cloudflare_model(&format!("{}/ai", server.uri()));
        let result = classify_cloudflare(&model, &oracle_context(), Some(&options())).await;
        assert_eq!(
            result.error_message.as_deref(),
            Some("Cloudflare Workers AI run did not complete (state: Running)")
        );

        // (3) cloudflare-failed: the errors array filters to message strings
        // and joins with "; ".
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "success": false,
                "errors": [{"message": "first"}, {"code": 7}, {"message": "second"}],
            })))
            .expect(1)
            .mount(&server)
            .await;
        let model = cloudflare_model(&format!("{}/ai", server.uri()));
        let result = classify_cloudflare(&model, &oracle_context(), Some(&options())).await;
        assert_eq!(
            result.error_message.as_deref(),
            Some("Cloudflare Workers AI error: first; second")
        );

        // (4) typesafe-missing-answer: one question without an answer fails
        // the whole result.
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .respond_with(
                ResponseTemplate::new(200).set_body_json(serde_json::json!({
                    "answers": {
                        "q1": {"type": "choice", "choice": "polite", "probabilities": {"polite": 0.8, "rude": 0.2}, "confidence": 0.6},
                        "q2": {"type": "score", "score": 1, "confidence": 0.5},
                    },
                })),
            )
            .expect(1)
            .mount(&server)
            .await;
        let model = typesafe_model(&format!("{}/", server.uri()));
        let result = classify_typesafe(&model, &oracle_context(), Some(&options())).await;
        assert_eq!(
            result.error_message.as_deref(),
            Some("System One API did not return an answer for q3")
        );
    }
}

// ---------------------------------------------------------------------------
// 3. model-catalog flatten over every embedded data shard
// ---------------------------------------------------------------------------
#[cfg(test)]
mod model_catalog {
    use super::*;
    use crate::ai::models::catalog::{
        catalog_provider_ids, embedded_provider_groups, flatten_typed_model_catalog,
    };
    use crate::ai::types::{AnyModel, ModelType};
    use std::collections::BTreeMap;

    fn sorted_map(models: Vec<AnyModel>) -> BTreeMap<String, Value> {
        let mut map = BTreeMap::new();
        for model in models {
            map.insert(
                model.id().to_string(),
                serde_json::to_value(&model).unwrap(),
            );
        }
        map
    }

    /// The chat flattening contract, pinned against the actual upstream
    /// `flattenChatModelCatalog` over every embedded shard: upstream keeps
    /// entries with `type === "chat"` STRICTLY (the current snapshot's
    /// untyped entries are all excluded), while the port additionally admits
    /// the untyped entries as chat — the documented compatibility rule that
    /// keeps the pre-discriminator snapshot resolving. Admitted entries match
    /// value-for-value.
    #[test]
    fn chat_flatten_matches_upstream_with_documented_untyped_rule() {
        let fixture = &oracle()["modelCatalog"];
        for provider in catalog_provider_ids() {
            let Some(expected) = fixture.get(provider) else {
                continue;
            };
            let groups = embedded_provider_groups(provider)
                .unwrap_or_else(|| panic!("{provider} missing from the embedded snapshot"));
            let actual = sorted_map(flatten_typed_model_catalog(
                provider,
                groups,
                ModelType::Chat,
            ));

            let mut expected_chat: BTreeMap<String, Value> = BTreeMap::new();
            for (id, model) in expected["chat"].as_object().unwrap() {
                expected_chat.insert(id.clone(), model.clone());
            }
            for group in groups.as_object().unwrap().values() {
                for (id, entry) in group.as_object().unwrap() {
                    if entry.get("type").is_none() {
                        expected_chat.insert(id.clone(), entry.clone());
                    }
                }
            }
            assert_eq!(actual, expected_chat, "{provider}: chat flatten diverges");
        }
    }

    /// Image and classifier flattening match upstream strictly (no untyped
    /// allowance): every embedded shard is empty on BOTH sides, and the
    /// synthetic mixed shard pins the strict per-type filter against the
    /// actual upstream semantics (`type === "image"` / `=== "classifier"`).
    #[test]
    fn image_and_classifier_flatten_match_upstream() {
        let fixture = &oracle()["modelCatalog"];
        for provider in catalog_provider_ids() {
            let Some(expected) = fixture.get(provider) else {
                continue;
            };
            let groups = embedded_provider_groups(provider).unwrap();
            let image = sorted_map(flatten_typed_model_catalog(
                provider,
                groups,
                ModelType::Image,
            ));
            let classifier = sorted_map(flatten_typed_model_catalog(
                provider,
                groups,
                ModelType::Classifier,
            ));
            let expected_image: BTreeMap<String, Value> = expected["image"]
                .as_object()
                .unwrap()
                .iter()
                .map(|(id, value)| (id.clone(), value.clone()))
                .collect();
            let expected_classifier: BTreeMap<String, Value> = expected["classifier"]
                .as_object()
                .unwrap()
                .iter()
                .map(|(id, value)| (id.clone(), value.clone()))
                .collect();
            assert_eq!(image, expected_image, "{provider} image");
            assert_eq!(classifier, expected_classifier, "{provider} classifier");
        }

        // The synthetic mixed shard: strict per-type selection on both sides
        // (upstream returns only the explicit `type` entries).
        let synthetic = serde_json::json!({
            "openai-completions": {
                "v1": {"id": "v1", "name": "V1", "api": "openai-completions", "provider": "p", "baseUrl": "https://p.example", "type": "chat", "reasoning": false, "input": ["text"], "cost": {"input": 1, "output": 2, "cacheRead": 0, "cacheWrite": 0}, "contextWindow": 8, "maxTokens": 4},
                "v2": {"id": "v2", "name": "V2", "api": "openai-completions", "provider": "p", "baseUrl": "https://p.example", "reasoning": false, "input": ["text"], "cost": {"input": 1, "output": 2, "cacheRead": 0, "cacheWrite": 0}, "contextWindow": 8, "maxTokens": 4}
            },
            "openrouter-images": {
                "i1": {"id": "i1", "name": "I1", "api": "openrouter-images", "provider": "p", "baseUrl": "https://p.example", "type": "image", "input": ["text"], "output": ["image"], "cost": {"input": 1, "output": 2, "cacheRead": 0, "cacheWrite": 0}}
            },
            "typesafe-system-one": {
                "c1": {"id": "c1", "name": "C1", "api": "typesafe-system-one", "provider": "p", "baseUrl": "https://p.example", "type": "classifier", "input": ["text"], "cost": {"input": 1, "output": 2, "cacheRead": 0, "cacheWrite": 0}, "contextWindow": 16}
            }
        });
        let expected = &fixture["<synthetic>"];
        // Upstream: only the explicit `type: "chat"` entry is a chat model;
        // the untyped v2 is excluded.
        let upstream_chat_keys: Vec<&str> = expected["chat"]
            .as_object()
            .unwrap()
            .keys()
            .map(String::as_str)
            .collect();
        assert_eq!(upstream_chat_keys, ["v1"]);
        assert_eq!(
            expected["image"]
                .as_object()
                .unwrap()
                .keys()
                .map(String::as_str)
                .collect::<Vec<_>>(),
            ["i1"]
        );
        assert_eq!(
            expected["classifier"]
                .as_object()
                .unwrap()
                .keys()
                .map(String::as_str)
                .collect::<Vec<_>>(),
            ["c1"]
        );
        // The port's strict image/classifier flatten agrees exactly (values
        // included).
        let image = sorted_map(flatten_typed_model_catalog(
            "p",
            &synthetic,
            ModelType::Image,
        ));
        let classifier = sorted_map(flatten_typed_model_catalog(
            "p",
            &synthetic,
            ModelType::Classifier,
        ));
        assert_eq!(image.len(), 1);
        assert_eq!(image["i1"], expected["image"]["i1"]);
        assert_eq!(classifier.len(), 1);
        assert_eq!(classifier["c1"], expected["classifier"]["c1"]);
        // And the port's chat flatten admits both the explicit and the
        // untyped chat entries (the documented superset rule).
        let chat = sorted_map(flatten_typed_model_catalog(
            "p",
            &synthetic,
            ModelType::Chat,
        ));
        let chat_keys: Vec<String> = chat.keys().cloned().collect();
        assert_eq!(chat_keys, vec!["v1".to_string(), "v2".to_string()]);
    }
}

// ---------------------------------------------------------------------------
// 4. v1.0.2 sampling-params surface (upstream 200387122)
// ---------------------------------------------------------------------------
#[cfg(test)]
mod sampling_params {
    //! Mirror of the `samplingParams` scenario (captured by
    //! `capture_ai_delta.mjs` from the `origin/main` blobs of
    //! `api/simple-options.ts` + `models.ts` under the disclosed stubs): the
    //! `resolveSamplingParams` grid, the `clampThinkingLevel` grid and
    //! supported sets, and the `buildBaseOptions` merge.

    use std::collections::BTreeMap;

    use serde_json::{json, Map, Value};

    use super::oracle;
    use crate::ai::api::openai_completions::request::{
        clamp_max_tokens_to_context, clamp_thinking_level, resolve_sampling_params,
    };
    use crate::ai::transcript::{normalize_context, Context, TranscriptContext};
    use crate::ai::types::model::Model;
    use crate::ai::types::primitives::ModelCost;
    use crate::ai::types::primitives::ThinkingLevel;

    fn oracle_scenario() -> Value {
        oracle()["samplingParams"].clone()
    }

    /// The capture's model base, rebuilt per shape (`full`, `bare`,
    /// `noLevels`, `nonReasoning`).
    fn oracle_model(name: &str) -> Model {
        Model {
            r#type: None,
            prompt_cache: None,
            input_limits: None,
            id: String::from("custom-model"),
            name: String::from("Custom Model"),
            api: String::from("openai-completions"),
            provider: String::from("custom"),
            base_url: String::from("https://api.example.com/v1"),
            reasoning: name != "nonReasoning",
            thinking_level_map: Some(BTreeMap::from([
                (String::from("low"), None),
                (String::from("medium"), None),
            ])),
            input: vec![crate::ai::types::ModelInput::Text],
            cost: ModelCost {
                input: 1.0,
                output: 2.0,
                cache_read: 0.0,
                cache_write: 0.0,
                tiers: None,
            },
            context_window: 128_000,
            max_tokens: 16_384,
            sampling_params: if name == "bare" {
                None
            } else {
                Some(BTreeMap::from([
                    (String::from("temperature"), json!(1)),
                    (String::from("top_p"), json!(0.95)),
                ]))
            },
            sampling_params_by_thinking_level: match name {
                "bare" | "noLevels" => None,
                _ => Some(BTreeMap::from([
                    (
                        String::from("high"),
                        BTreeMap::from([
                            (String::from("temperature"), json!(0.8)),
                            (String::from("top_k"), json!(64)),
                        ]),
                    ),
                    (
                        String::from("off"),
                        BTreeMap::from([(String::from("temperature"), json!(0.7))]),
                    ),
                ])),
            },
            headers: None,
            compat: None,
        }
    }

    fn level_of(wire: &str) -> Option<ThinkingLevel> {
        match wire {
            "off" => None,
            "minimal" => Some(ThinkingLevel::Minimal),
            "low" => Some(ThinkingLevel::Low),
            "medium" => Some(ThinkingLevel::Medium),
            "high" => Some(ThinkingLevel::High),
            "xhigh" => Some(ThinkingLevel::Xhigh),
            "max" => Some(ThinkingLevel::Max),
            other => panic!("unexpected level {other}"),
        }
    }

    fn empty_context() -> TranscriptContext {
        normalize_context(&Context {
            system_prompt: None,
            messages: Vec::new(),
            tools: None,
        })
    }

    /// The full `resolveSamplingParams` grid (model shape x level x request
    /// keys), compared entry-for-entry in capture order.
    #[test]
    fn resolve_grid_matches_upstream() {
        let expected = oracle_scenario()["resolve"].as_array().unwrap().clone();
        let models = ["full", "bare", "noLevels", "nonReasoning"];
        let levels = ["off", "minimal", "low", "medium", "high", "xhigh", "max"];
        let request = BTreeMap::from([(String::from("top_k"), json!(1))]);
        let mut actual = Vec::new();
        for model_name in models {
            let model = oracle_model(model_name);
            for level in levels {
                for request_wire in [json!(null), json!({"top_k": 1})] {
                    let request_params = if request_wire.is_null() {
                        None
                    } else {
                        Some(&request)
                    };
                    let result = resolve_sampling_params(&model, level_of(level), request_params);
                    actual.push(json!({
                        "model": model_name,
                        "level": level,
                        "request": request_wire,
                        "result": result
                            .map(|params| Value::Object(params.into_iter().collect())),
                    }));
                }
            }
        }
        assert_eq!(Value::Array(actual), Value::Array(expected), "resolve grid");
    }

    /// `clampThinkingLevel` per model and the supported set it derives from
    /// (a level is supported exactly when the clamp is the identity).
    #[test]
    fn clamp_and_supported_match_upstream() {
        let expected = oracle_scenario();
        let models = ["full", "bare", "noLevels", "nonReasoning"];
        let levels = ["off", "minimal", "low", "medium", "high", "xhigh", "max"];
        for model_name in models {
            let model = oracle_model(model_name);
            let wire = |level: Option<ThinkingLevel>| match level {
                None => json!("off"),
                Some(level) => json!(serde_json::to_value(level).unwrap()),
            };
            for level in levels {
                assert_eq!(
                    wire(clamp_thinking_level(&model, level_of(level))),
                    expected["clamped"][model_name][level],
                    "clamped[{model_name}][{level}]"
                );
            }
            let supported: Vec<Value> = levels
                .iter()
                .filter(|level| clamp_thinking_level(&model, level_of(level)) == level_of(level))
                .map(|level| json!(level))
                .collect();
            assert_eq!(
                Value::Array(supported),
                expected["supported"][model_name].clone(),
                "supported[{model_name}]"
            );
        }
    }

    /// `buildBaseOptions`: the resolved `samplingParams` member and the
    /// context-clamped `maxTokens` for the reasoning request with per-request
    /// keys, and for the bare model with no sampling configuration.
    #[test]
    fn build_base_options_matches_upstream() {
        let expected = oracle_scenario();
        let ctx = empty_context();

        let full = oracle_model("full");
        let request = BTreeMap::from([(String::from("top_p"), json!(0.5))]);
        let resolved = resolve_sampling_params(&full, Some(ThinkingLevel::Low), Some(&request));
        // JSON.stringify drops the undefined member; mirror that shape.
        let mut base = Map::new();
        if let Some(params) = resolved {
            base.insert(
                String::from("samplingParams"),
                Value::Object(params.into_iter().collect()),
            );
        }
        base.insert(
            String::from("maxTokens"),
            json!(clamp_max_tokens_to_context(&full, &ctx, full.max_tokens)),
        );
        assert_eq!(Value::Object(base), expected["base"], "base");

        let bare = oracle_model("bare");
        let mut base_bare = Map::new();
        if let Some(params) = resolve_sampling_params(&bare, Some(ThinkingLevel::Low), None) {
            base_bare.insert(
                String::from("samplingParams"),
                Value::Object(params.into_iter().collect()),
            );
        }
        base_bare.insert(
            String::from("maxTokens"),
            json!(clamp_max_tokens_to_context(&bare, &ctx, bare.max_tokens)),
        );
        assert_eq!(Value::Object(base_bare), expected["baseBare"], "baseBare");
    }
}
