//! Upstream `flattenModelCatalog` (`packages/ai/src/model-catalog.ts`) plus the
//! embedded generated-catalog loading that upstream does with per-provider
//! `import ... with { type: "json" }` statements (`providers/*.models.ts`,
//! aggregated by `providers/all.ts`) and the `data/.manifest.json` generation
//! manifest (`scripts/model-data.ts` types).
//!
//! # Embedded data
//!
//! The snapshot lives in `assets/model-data/` (38 provider files, one JSON
//! document per provider, shape `{api: {modelId: Model}}`) and is embedded at
//! compile time through an include-list generated by `build.rs` — the Rust
//! equivalent of upstream's generated `*.models.ts` shard imports. The files
//! are byte-identical to upstream's committed `providers/data/*.json`
//! (verified: every SHA-256 in the manifest matches), and `.manifest.json` is
//! upstream's own manifest for exactly that data (`generatedAt`
//! `2026-09-21T02:08:23.378Z`). Data provenance: the snapshot was generated
//! from live models.dev on 2026-09-21; `kimi-coding` is absent from the live
//! source, so it deliberately has no catalog here (config-declared models
//! cover it) and `radius` is a dynamic provider with no static catalog.
//!
//! # Ordering and dedup
//!
//! Upstream `flattenModelCatalog` returns a record:
//! `Object.assign({}, ...Object.values(groups))` — all API groups merged by
//! copying own enumerable string-keyed properties in group order; a
//! duplicate model id across groups resolves last-wins (the later group's
//! value overwrites) while the key keeps its first-insertion position. The Rust port
//! returns `Vec<Model>` sorted by model id: serde_json objects are sorted
//! maps, so upstream's first-appearance record order is not representable, and
//! the collection layer (Task 2) wants a deterministic list. The model set and
//! the winning values are identical to upstream; only iteration order differs.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::sync::OnceLock;

use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::ai::types::Model;

/// The build-time generated include-list (see `build.rs`).
mod embedded {
    include!(concat!(env!("OUT_DIR"), "/model_data.rs"));
}

/// Upstream `MODEL_DATA_SCHEMA_VERSION` (`scripts/model-data.ts:5`).
pub const MODEL_DATA_SCHEMA_VERSION: u32 = 3;

/// Upstream `MODEL_DATA_MANIFEST_FILE` (`scripts/model-data.ts:6`).
pub const MODEL_DATA_MANIFEST_FILE: &str = ".manifest.json";

/// Upstream `ModelDataStructure` (`scripts/model-data.ts:8`): provider id →
/// model id → API group. Sorted maps keep the serialization byte-compatible
/// with the upstream generator's sorted records.
pub type ModelDataStructure = BTreeMap<String, BTreeMap<String, String>>;

/// Upstream `ModelDataManifest` (`scripts/model-data.ts:10-15`): provenance
/// stamp for one generated catalog snapshot.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModelDataManifest {
    /// Embedded data schema version (see [`MODEL_DATA_SCHEMA_VERSION`]).
    pub schema_version: u32,
    /// Generator timestamp, ISO-8601 (`Date.parse`-able upstream).
    pub generated_at: String,
    /// SHA-256 over the sorted api-structure map (see
    /// [`model_data_structure_hash`]).
    pub structure_hash: String,
    /// SHA-256 per provider data file name (`.manifest.json` excluded).
    pub files: BTreeMap<String, String>,
}

/// The embedded generation manifest (one-time parse of the constant JSON).
pub fn model_data_manifest() -> &'static ModelDataManifest {
    static MANIFEST: OnceLock<ModelDataManifest> = OnceLock::new();
    MANIFEST.get_or_init(|| {
        serde_json::from_str(embedded::MODEL_DATA_MANIFEST)
            .expect("embedded model data manifest must deserialize")
    })
}

/// The embedded catalog's api-structure map: every provider's
/// `{modelId: api}` grouping, derived from the embedded data files (one-time).
///
/// Port of upstream `readProviderStructure` per shard; a model id appearing in
/// more than one API group is generator-bug territory and panics, exactly like
/// the upstream validator throws.
pub fn model_data_structure() -> &'static ModelDataStructure {
    static STRUCTURE: OnceLock<ModelDataStructure> = OnceLock::new();
    STRUCTURE.get_or_init(|| {
        let mut structure = ModelDataStructure::new();
        for &(provider_id, json) in embedded::MODEL_DATA_FILES {
            let groups: serde_json::Value = serde_json::from_str(json)
                .unwrap_or_else(|error| panic!("{provider_id}.json is not valid JSON: {error}"));
            let mut models = BTreeMap::new();
            let group_object = groups
                .as_object()
                .unwrap_or_else(|| panic!("{provider_id}.json must contain a JSON object"));
            for (api, value) in group_object {
                let group = value
                    .as_object()
                    .unwrap_or_else(|| panic!("{provider_id}.json API group {api:?} must be an object"));
                for model_id in group.keys() {
                    if models.insert(model_id.clone(), api.clone()).is_some() {
                        panic!("{provider_id}.json contains model {model_id} in more than one API group");
                    }
                }
            }
            if models.is_empty() {
                panic!("{provider_id}.json contains no generated model data");
            }
            structure.insert(provider_id.to_string(), models);
        }
        structure
    })
}

/// All provider ids present in the embedded catalog, sorted (one per data
/// file). Dynamic providers without a generated shard (`radius`) and the
/// drifted `kimi-coding` are absent.
pub fn catalog_provider_ids() -> impl Iterator<Item = &'static str> {
    embedded::MODEL_DATA_FILES.iter().map(|(id, _)| *id)
}

/// The embedded `{api: {modelId: Model}}` document for one provider, parsed
/// once and cached. `None` when the provider has no generated shard.
pub fn embedded_provider_groups(provider: &str) -> Option<&'static serde_json::Value> {
    static GROUPS: OnceLock<BTreeMap<&'static str, serde_json::Value>> = OnceLock::new();
    let groups = GROUPS.get_or_init(|| {
        embedded::MODEL_DATA_FILES
            .iter()
            .map(|(id, json)| {
                (
                    *id,
                    serde_json::from_str(json)
                        .unwrap_or_else(|error| panic!("{id}.json is not valid JSON: {error}")),
                )
            })
            .collect()
    });
    groups.get(provider)
}

/// Upstream `getBuiltinModels` (`providers/all.ts`): the provider's flattened
/// catalog, or an empty list when the provider has no generated shard.
pub fn embedded_provider_catalog(provider: &str) -> Vec<Model> {
    match embedded_provider_groups(provider) {
        Some(groups) => flatten_model_catalog(provider, groups),
        None => Vec::new(),
    }
}

/// Upstream `flattenModelCatalog` (`packages/ai/src/model-catalog.ts:22-27`):
/// merge every API group into one flat model list.
///
/// `_provider` mirrors the upstream parameter — it is a type-level input only
/// (`flattenModelCatalog<const TProvider ...>`) and takes no part in the
/// runtime merge. Group values that are not JSON objects are skipped — a
/// port-side defensive choice, not `Object.assign` runtime behavior (upstream
/// would throw on non-iterable primitives and spread strings/arrays into
/// index keys; only null/undefined are ignored — and the `ModelGroups` type
/// plus the structure validator make non-object groups unreachable for
/// generated data). Duplicate model ids across groups are
/// resolved last-wins like `Object.assign`; the returned list is sorted by
/// model id (see the module docs). Model JSON that fails to deserialize panics
/// with the offending provider/model: upstream catches malformed generated
/// data at build time through the type system, and the embedded data here is
/// equally constant (`validate_embedded_catalog` re-checks it in tests).
pub fn flatten_model_catalog(_provider: &str, groups: &serde_json::Value) -> Vec<Model> {
    let mut merged: BTreeMap<&str, &serde_json::Value> = BTreeMap::new();
    if let Some(groups) = groups.as_object() {
        for (_api, group) in groups {
            if let Some(group) = group.as_object() {
                for (model_id, value) in group {
                    merged.insert(model_id.as_str(), value);
                }
            }
        }
    }
    merged
        .into_iter()
        .map(|(model_id, value)| {
            Model::deserialize(value).unwrap_or_else(|error| {
                panic!("{_provider}/{model_id} is not a valid generated model: {error}")
            })
        })
        .collect()
}

/// Upstream `modelDataStructureHash` (`scripts/model-data.ts:118-125`):
/// SHA-256 over the compact JSON serialization of the sorted structure. The
/// port must stay byte-compatible with the generator's
/// `JSON.stringify(sortedRecord(...))` so manifest stamps verify — serde_json
/// emits identical bytes for these ASCII identifier strings.
pub fn model_data_structure_hash(structure: &ModelDataStructure) -> String {
    let serialized = serde_json::to_string(structure).expect("structure serialization cannot fail");
    let mut hasher = Sha256::new();
    hasher.update(serialized.as_bytes());
    hex(&hasher.finalize())
}

/// Upstream `validateModelDataDirectory` (`scripts/model-data.ts:193-274`)
/// reduced to what applies to the embedded snapshot (there is no on-disk
/// directory to re-read): schema version, generation timestamp, structure and
/// per-file hashes against the manifest, and every model value matching its
/// generated key/`provider`/`api` plus the non-deser bounds
/// (`name`, non-empty `input`, positive `contextWindow`/`maxTokens`) that the
/// upstream validator enforces beyond the TypeScript type.
pub fn validate_embedded_catalog() -> Result<(), String> {
    let mut errors: Vec<String> = Vec::new();
    let manifest = model_data_manifest();

    if manifest.schema_version != MODEL_DATA_SCHEMA_VERSION {
        errors.push(format!(
            "model data schema is {}, expected {MODEL_DATA_SCHEMA_VERSION}",
            manifest.schema_version
        ));
    }
    if !generated_at_parses(&manifest.generated_at) {
        errors.push("model data manifest has an invalid generation timestamp".to_string());
    }

    let structure = model_data_structure();
    if manifest.structure_hash != model_data_structure_hash(structure) {
        errors.push("model data generation stamp does not match the generated catalog".to_string());
    }

    // Upstream sorts expected file *names* (`readdirSync` + `sort`); byte
    // order puts `google-vertex.json` before `google.json`, so sort the names,
    // not the provider ids.
    let mut expected_files: Vec<String> = catalog_provider_ids()
        .map(|id| format!("{id}.json"))
        .collect();
    expected_files.sort();
    if manifest
        .files
        .keys()
        .map(String::as_str)
        .ne(expected_files.iter().map(String::as_str))
    {
        errors.push("manifest file hashes do not match provider data files".to_string());
    }
    for &(provider_id, json) in embedded::MODEL_DATA_FILES {
        let filename = format!("{provider_id}.json");
        let Some(expected_hash) = manifest.files.get(&filename) else {
            errors.push(format!("{filename} is missing from the manifest"));
            continue;
        };
        if *expected_hash != sha256_hex(json.as_bytes()) {
            errors.push(format!("{filename} does not match its manifest hash"));
        }
        validate_provider_models(provider_id, json, structure.get(provider_id), &mut errors);
    }

    if errors.is_empty() {
        return Ok(());
    }
    let visible: Vec<String> = errors.iter().take(30).map(|e| format!("  - {e}")).collect();
    let suffix = if errors.len() > visible.len() {
        format!("\n  ... and {} more", errors.len() - visible.len())
    } else {
        String::new()
    };
    Err(format!(
        "Invalid generated model data:\n{}{suffix}",
        visible.join("\n")
    ))
}

/// Per-provider half of upstream `validateModelValue`: deserialize every model
/// and check the identity/bound fields serde cannot infer from the catalog key.
fn validate_provider_models(
    provider_id: &str,
    json: &str,
    expected: Option<&BTreeMap<String, String>>,
    errors: &mut Vec<String>,
) {
    let Ok(groups) = serde_json::from_str::<serde_json::Value>(json) else {
        errors.push(format!("{provider_id}.json is not valid JSON"));
        return;
    };
    let Some(groups) = groups.as_object() else {
        errors.push(format!("{provider_id}.json must contain a JSON object"));
        return;
    };

    let mut model_ids: Vec<&String> = Vec::new();
    for (api, value) in groups {
        let Some(group) = value.as_object() else {
            errors.push(format!(
                "{provider_id}.json API group {api:?} must be an object"
            ));
            continue;
        };
        for (model_id, model) in group {
            model_ids.push(model_id);
            let label = format!("{provider_id}/{model_id}");
            let Ok(model) = Model::deserialize(model) else {
                errors.push(format!("{label} does not deserialize into a Model"));
                continue;
            };
            if model.id != *model_id {
                errors.push(format!(
                    "{label} has id {:?}, expected {model_id:?}",
                    model.id
                ));
            }
            if model.provider != provider_id {
                errors.push(format!(
                    "{label} has provider {:?}, expected {provider_id:?}",
                    model.provider
                ));
            }
            if model.api != *api {
                errors.push(format!("{label} has api {:?}, expected {api:?}", model.api));
            }
            if model.name.is_empty() {
                errors.push(format!("{label} has no model name"));
            }
            if model.input.is_empty() {
                errors.push(format!("{label} has invalid input modalities"));
            }
            if model.context_window == 0 {
                errors.push(format!("{label} has invalid contextWindow"));
            }
            if model.max_tokens == 0 {
                errors.push(format!("{label} has invalid maxTokens"));
            }
        }
    }

    let Some(expected) = expected else {
        errors.push(format!(
            "{provider_id}.json is missing from the generated catalog"
        ));
        return;
    };
    model_ids.sort();
    if model_ids
        .iter()
        .map(|id| id.as_str())
        .ne(expected.keys().map(String::as_str))
    {
        errors.push(format!(
            "{provider_id}.json model IDs do not match the generated catalog"
        ));
    }
    // Duplicate ids across groups are rejected by `model_data_structure`, so
    // at most one group holds any given model id.
    for (model_id, expected_api) in expected {
        let actual_api = groups.iter().find_map(|(api, value)| {
            value
                .as_object()
                .is_some_and(|group| group.contains_key(model_id))
                .then_some(api)
        });
        let Some(actual_api) = actual_api else {
            continue;
        };
        if actual_api != expected_api {
            errors.push(format!(
                "{provider_id}/{model_id} is grouped under API {actual_api:?}, expected {expected_api:?}"
            ));
        }
    }
}

/// Narrow port of the manifest timestamp check
/// (`Number.isNaN(Date.parse(generatedAt))`): the generator emits exactly one
/// shape, ISO-8601 UTC `YYYY-MM-DDTHH:MM:SS[.fff…]Z`. Documented divergence:
/// upstream `Date.parse` returns `NaN` for impossible calendar dates (day 30
/// of February), while the parser here accepts any `01`-`31` day shape
/// regardless of month length — deliberate, since the only input is the
/// generated manifest stamp, whose components always cohere. Delegates to the
/// shared generator-shape parser ([`crate::ai::models::providers::parse_iso_utc_ms`])
/// so the acceptance set and the epoch conversion live in one place.
fn generated_at_parses(value: &str) -> bool {
    crate::ai::models::providers::parse_iso_utc_ms(value).is_some()
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hex(&hasher.finalize())
}

fn hex(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        let _ = write!(out, "{byte:02x}");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// Minimal generated-model wire shape (all required `Model` fields).
    fn model_json(id: &str, api: &str, context_window: u64) -> serde_json::Value {
        json!({
            "id": id,
            "name": "Test Model",
            "api": api,
            "provider": "test-provider",
            "baseUrl": "https://example.test/v1",
            "reasoning": false,
            "input": ["text"],
            "cost": {"input": 1, "output": 2, "cacheRead": 0, "cacheWrite": 0},
            "contextWindow": context_window,
            "maxTokens": 100
        })
    }

    #[test]
    fn flatten_merges_api_groups_into_sorted_models() {
        let groups = json!({
            "openai-responses": {
                "b-model": model_json("b-model", "openai-responses", 2000),
                "a-model": model_json("a-model", "openai-responses", 1000),
            },
            "anthropic-messages": {
                "c-model": model_json("c-model", "anthropic-messages", 3000),
            }
        });
        let models = flatten_model_catalog("test-provider", &groups);
        let ids: Vec<&str> = models.iter().map(|m| m.id.as_str()).collect();
        assert_eq!(ids, ["a-model", "b-model", "c-model"]);
        assert_eq!(models[0].context_window, 1000);
        assert_eq!(models[2].api, "anthropic-messages");
    }

    #[test]
    fn flatten_resolves_duplicate_model_ids_last_group_wins() {
        // Object.assign merge: a duplicate id resolves to the value from the
        // later group in iteration order. serde_json objects iterate in sorted
        // key order, so "openai-completions" is the later group here (upstream
        // iterates JSON insertion order; the generator rejects duplicate ids
        // across groups, so valid data never hits this).
        let groups = json!({
            "anthropic-messages": {"dup": model_json("dup", "anthropic-messages", 1000)},
            "openai-completions": {"dup": model_json("dup", "openai-completions", 2000)},
        });
        let models = flatten_model_catalog("test-provider", &groups);
        assert_eq!(models.len(), 1);
        assert_eq!(models[0].api, "openai-completions");
        assert_eq!(models[0].context_window, 2000);
    }

    #[test]
    fn flatten_skips_non_object_group_values_defensively() {
        let groups = json!({
            "openai-completions": {"a": model_json("a", "openai-completions", 1000)},
            "bogus": 3,
            "also-bogus": "x",
            "null-group": null,
        });
        let models = flatten_model_catalog("test-provider", &groups);
        assert_eq!(models.len(), 1);
        assert_eq!(models[0].id, "a");

        assert!(flatten_model_catalog("test-provider", &json!(3)).is_empty());
    }

    #[test]
    fn embedded_catalog_lists_every_provider_snapshot_shard() {
        let ids: Vec<&str> = catalog_provider_ids().collect();
        assert_eq!(ids.len(), model_data_structure().len());
        assert!(
            ids.windows(2).all(|pair| pair[0] < pair[1]),
            "ids must be sorted"
        );
        assert!(ids.contains(&"openai"));
        assert!(ids.contains(&"xai"));
        assert!(ids.contains(&"github-copilot"));
        assert!(ids.contains(&"openrouter"));
        // radius is a dynamic provider with no generated shard, and
        // kimi-coding is absent from the live models.dev snapshot (disclosed
        // drift): neither ships catalog data.
        assert!(!ids.contains(&"radius"));
        assert!(!ids.contains(&"kimi-coding"));
    }

    #[test]
    fn embedded_provider_catalog_flattens_the_snapshot() {
        let xai = embedded_provider_catalog("xai");
        let ids: Vec<&str> = xai.iter().map(|m| m.id.as_str()).collect();
        assert_eq!(ids, ["grok-4.3", "grok-4.5", "grok-4.6"]);
        assert!(xai.iter().all(|m| m.provider == "xai"));

        // Providers without a generated shard get an empty catalog.
        assert!(embedded_provider_catalog("nope").is_empty());
        assert!(embedded_provider_catalog("kimi-coding").is_empty());
        assert!(embedded_provider_groups("nope").is_none());
        assert!(embedded_provider_groups("xai").is_some());
    }

    #[test]
    fn validation_passes_on_the_embedded_snapshot() {
        validate_embedded_catalog().expect("embedded snapshot must validate");

        // Counts match the manifest's api-structure map.
        let structure = model_data_structure();
        let total: usize = structure.values().map(|models| models.len()).sum();
        assert_eq!(structure.len(), embedded::MODEL_DATA_FILES.len());
        assert!(total > 1000, "snapshot unexpectedly small: {total}");
        assert_eq!(structure["xai"].len(), 3);
        assert_eq!(structure["openrouter"].len(), 380);
        let manifest = model_data_manifest();
        assert_eq!(manifest.schema_version, MODEL_DATA_SCHEMA_VERSION);
        assert_eq!(
            manifest.structure_hash,
            model_data_structure_hash(structure)
        );
    }

    #[test]
    fn generated_at_accepts_generator_shape_and_rejects_garbage() {
        assert!(generated_at_parses(&model_data_manifest().generated_at));
        assert!(generated_at_parses("2026-07-23T10:00:00.000Z"));
        assert!(generated_at_parses("2026-07-23T10:00:00Z"));
        assert!(!generated_at_parses("invalid"));
        assert!(!generated_at_parses("2026-13-23T10:00:00.000Z"));
        assert!(!generated_at_parses("2026-07-23T25:00:00.000Z"));
        assert!(!generated_at_parses("2026-07-23 10:00:00.000Z"));
        assert!(!generated_at_parses("2026-07-23T10:00:00.000"));
    }

    /// Data halves of upstream `model-catalog-types.test.ts` ("derives model
    /// API, ID, and provider literals from grouped model data").
    #[test]
    fn xai_catalog_routes_grok_models_through_openai_responses() {
        let xai = embedded_provider_catalog("xai");
        let grok = |id: &str| {
            xai.iter()
                .find(|m| m.id == id)
                .unwrap_or_else(|| panic!("{id} missing"))
        };
        assert_eq!(grok("grok-4.5").api, "openai-responses");
        assert_eq!(grok("grok-4.5").id, "grok-4.5");
        assert_eq!(grok("grok-4.5").provider, "xai");
        assert_eq!(grok("grok-4.6").api, "openai-responses");
        assert_eq!(grok("grok-4.6").id, "grok-4.6");
        assert_eq!(grok("grok-4.3").api, "openai-responses");
    }

    /// Data halves of upstream `model-catalog-types.test.ts` ("routes GitHub
    /// Copilot Grok 4.5 through the Responses API").
    #[test]
    fn github_copilot_routes_grok_45_through_openai_responses() {
        let ghcp = embedded_provider_catalog("github-copilot");
        let grok = ghcp
            .iter()
            .find(|m| m.id == "grok-4.5")
            .expect("github-copilot grok-4.5");
        assert_eq!(grok.api, "openai-responses");
    }

    /// Data half of upstream `model-catalog-types.test.ts` ("Regression test
    /// for https://github.com/earendil-works/pi/issues/9209": all GitHub
    /// Copilot GPT models route through the Responses API).
    #[test]
    fn github_copilot_routes_all_gpt_models_through_openai_responses() {
        let ghcp = embedded_provider_catalog("github-copilot");
        let gpt: Vec<&Model> = ghcp.iter().filter(|m| m.id.starts_with("gpt-")).collect();
        assert!(!gpt.is_empty());
        assert!(
            gpt.iter().all(|m| m.api == "openai-responses"),
            "every gpt-* model must use openai-responses"
        );
        assert!(gpt.iter().any(|m| m.id == "gpt-6-astra"));
    }
}
