//! Byte-oracle tests for the codemode slice: every expectation was captured by
//! EXECUTING the actual upstream TypeScript (2bbfcca43, pi-codemode 0.99.1)
//! under Node `--experimental-strip-types` — see
//! `tests/fixtures/codemode_oracle/capture_codemode_oracle.mjs` (the
//! generator, kept with the fixture) and `codemode_oracle.manifest.json` (the
//! SHA-256 provenance of every captured source; the manifest hashes are
//! re-verified against the committed byte-exact fixture copies by
//! [`manifest_hashes_match_upstream`], and the copies were verified against
//! the upstream tree when captured).
//!
//! Part A replays each captured script (inputs are part of the fixture) through
//! the Rust sandbox ([`CodemodeSandbox`], rquickjs) and compares values
//! (canonical JSON), output items, calls (name/status in order; `durationMs`
//! is wall-clock, asserted non-negative), store writes, and error
//! kind/name/message/stack — the stacks included, since the engines share the
//! quickjs-ng core and the capture's frame texts are byte-identical here (see
//! the engine module docs). Part B pins the extension description pipeline
//! (`create_codemode_description` / `render_tool_sample`) against the verbatim
//! captured `tool.ts`. Part C pins [`parse_codemode_source`]; the invalid-JSON
//! message embeds the host JSON parser's text (V8 upstream, `serde_json`
//! here) and is classified instead, as disclosed on
//! [`CodemodeSourceError`](crate::codemode::source::CodemodeSourceError).

use std::collections::BTreeMap;
use std::sync::Arc;

use serde_json::{json, Value};

use crate::codemode::declarations::{render_tool_sample, Declarable};
use crate::codemode::source::parse_codemode_source;
use crate::codemode::types::{
    CodemodeCall, CodemodeExecuteOptions, CodemodeOutputItem, CodemodeResult,
    CodemodeSandboxOptions, CodemodeTool,
};
use crate::codemode::CodemodeSandbox;

/// The captured fixture (generated by the committed capture script against
/// upstream 2bbfcca43).
fn oracle() -> Value {
    serde_json::from_str(include_str!(
        "../../tests/fixtures/codemode_oracle/codemode_oracle.json"
    ))
    .expect("oracle fixture must parse")
}

/// SHA-256 hex of a byte slice (the capture pins upstream sources by hash).
fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::Digest;
    let digest = sha2::Sha256::digest(bytes);
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

/// Re-verifies the manifest's upstream source hashes against the byte-exact
/// fixture copies (which themselves were verified against the upstream tree
/// when captured; the copies are committed, so hashing them here pins the
/// provenance chain against fixture drift).
#[test]
fn manifest_hashes_match_upstream() {
    let manifest: Value = serde_json::from_str(include_str!(
        "../../tests/fixtures/codemode_oracle/codemode_oracle.manifest.json"
    ))
    .expect("manifest must parse");
    for (path, expected) in manifest["upstreamSources"]
        .as_object()
        .expect("manifest upstreamSources")
        .into_iter()
        .filter(|(path, _)| path.ends_with(".ts"))
    {
        let file_name = path.rsplit('/').next().expect("file name");
        let bytes = if let Some(rest) = path.strip_prefix("packages/codemode/src/") {
            std::fs::read(format!(
                "{}/tests/fixtures/codemode_oracle/src/{rest}",
                env!("CARGO_MANIFEST_DIR")
            ))
        } else {
            std::fs::read(format!(
                "{}/tests/fixtures/codemode_oracle/upstream-closure/extensions/codemode/{file_name}",
                env!("CARGO_MANIFEST_DIR")
            ))
        };
        let bytes = bytes.unwrap_or_else(|error| panic!("{path}: {error}"));
        assert_eq!(
            sha256_hex(&bytes),
            expected.as_str().expect("hex digest"),
            "fixture copy of {path} drifted from the captured upstream hash"
        );
    }
}

// ---------------------------------------------------------------------------
// Part A: script execution through the sandbox
// ---------------------------------------------------------------------------

/// The capture's tool set (mirrors capture_codemode_oracle.mjs; deterministic
/// executions only). `pending` never settles.
fn capture_tools() -> Vec<CodemodeTool> {
    fn tool(
        name: &str,
        description: &str,
        execute: impl Fn(Option<Value>) -> Result<Option<Value>, String> + Send + Sync + 'static,
    ) -> CodemodeTool {
        CodemodeTool {
            name: name.to_string(),
            description: Some(description.to_string()),
            input_schema: None,
            output_schema: None,
            spread: false,
            signature: None,
            execute: Arc::new(move |args, _context| Box::pin(std::future::ready(execute(args)))),
        }
    }
    vec![
        tool("add", "Adds two numbers.", |args| {
            let a = args
                .as_ref()
                .and_then(|value| value.get("a"))
                .and_then(Value::as_f64);
            let b = args
                .as_ref()
                .and_then(|value| value.get("b"))
                .and_then(Value::as_f64);
            match (a, b) {
                (Some(a), Some(b)) => Ok(Some(json!({ "sum": a + b }))),
                _ => Err("add expects numeric a and b".to_string()),
            }
        }),
        tool("echo", "Returns the arguments unchanged.", |args| {
            Ok(Some(args.unwrap_or(Value::Null)))
        }),
        tool("fail", "Always throws.", |_| Err("tool boom".to_string())),
        tool("fail_string", "Throws a non-Error value.", |_| {
            Err("plain string throw".to_string())
        }),
        // `execute: () => new Promise(() => {})` — the future never resolves.
        CodemodeTool {
            name: "pending".to_string(),
            description: Some("Never settles.".to_string()),
            input_schema: None,
            output_schema: None,
            spread: false,
            signature: None,
            execute: Arc::new(|_args, _context| Box::pin(std::future::pending())),
        },
        tool("slow_add", "Adds after a short delay.", |args| {
            let sum = args
                .as_ref()
                .and_then(|value| value.get("a"))
                .and_then(Value::as_f64)
                .unwrap_or(0.0)
                + args
                    .as_ref()
                    .and_then(|value| value.get("b"))
                    .and_then(Value::as_f64)
                    .unwrap_or(0.0);
            Ok(Some(json!({ "sum": sum })))
        }),
    ]
}

/// The capture's global set.
fn capture_globals() -> Vec<CodemodeTool> {
    vec![
        CodemodeTool {
            name: "helper".to_string(),
            description: Some("Wraps a value.".to_string()),
            input_schema: None,
            output_schema: None,
            spread: false,
            signature: None,
            execute: Arc::new(|args, _context| {
                Box::pin(std::future::ready(Ok(Some(json!({
                    "wrapped": args.unwrap_or(Value::Null)
                })))))
            }),
        },
        CodemodeTool {
            name: "spread_all".to_string(),
            description: Some("Returns all call arguments.".to_string()),
            input_schema: None,
            output_schema: None,
            spread: true,
            signature: None,
            execute: Arc::new(|args, _context| Box::pin(std::future::ready(Ok(args)))),
        },
        CodemodeTool {
            name: "ns.member".to_string(),
            description: Some("Namespaced member.".to_string()),
            input_schema: None,
            output_schema: None,
            spread: false,
            signature: None,
            execute: Arc::new(|args, _context| {
                Box::pin(std::future::ready(Ok(Some(json!(format!(
                    "member:{}",
                    serde_json::to_string(&args.unwrap_or(Value::Null))
                        .unwrap_or_else(|_| "null".to_string())
                ))))))
            }),
        },
    ]
}

fn capture_sandbox(timeout_ms: Option<u64>, memory_limit_bytes: Option<usize>) -> CodemodeSandbox {
    CodemodeSandbox::new(CodemodeSandboxOptions {
        tools: capture_tools(),
        globals: capture_globals(),
        timeout_ms,
        memory_limit_bytes,
    })
    .expect("capture sandbox registers")
}

/// The pinned calls: name/status in order, duration non-negative.
fn assert_calls(label: &str, actual: &[CodemodeCall], expected: &Value) {
    let expected = expected.as_array().cloned().unwrap_or_default();
    assert_eq!(
        actual.len(),
        expected.len(),
        "{label}: call count mismatch (actual {actual:?})"
    );
    for (actual, expected) in actual.iter().zip(&expected) {
        assert_eq!(
            actual.name,
            expected["name"].as_str().unwrap(),
            "{label}: call name"
        );
        assert_eq!(
            actual.status,
            serde_json::from_value(expected["status"].clone()).unwrap(),
            "{label}: call status"
        );
        assert!(actual.duration_ms >= 0.0, "{label}: duration sign");
    }
}

/// The pinned output items, byte-exact.
fn assert_output(label: &str, actual: &[CodemodeOutputItem], expected: &Value) {
    let expected = expected.as_array().cloned().unwrap_or_default();
    assert_eq!(actual.len(), expected.len(), "{label}: output item count");
    for (item, expected) in actual.iter().zip(&expected) {
        match item {
            CodemodeOutputItem::Text { text } => {
                assert_eq!(expected["type"].as_str(), Some("text"), "{label}");
                assert_eq!(
                    text,
                    expected["text"].as_str().unwrap_or_default(),
                    "{label}: text"
                );
            }
            CodemodeOutputItem::Image { data, mime_type } => {
                assert_eq!(expected["type"].as_str(), Some("image"), "{label}");
                assert_eq!(
                    data,
                    expected["data"].as_str().unwrap_or_default(),
                    "{label}: image data"
                );
                assert_eq!(
                    mime_type,
                    expected["mimeType"].as_str().unwrap_or_default(),
                    "{label}: image mime"
                );
            }
        }
    }
}

/// The pinned error: kind exact, name/message exact, stack exact when the
/// capture pinned one (same quickjs-ng core; see the module docs).
fn assert_error(label: &str, result: &CodemodeResult, expected: &Value) {
    let CodemodeResult::Err { error, .. } = result else {
        panic!("{label}: expected a failed execution");
    };
    let expected_kind: crate::codemode::types::CodemodeErrorKind =
        serde_json::from_value(expected["kind"].clone()).expect("error kind");
    assert_eq!(error.kind, expected_kind, "{label}: error kind");
    if let Some(name) = expected.get("name").and_then(Value::as_str) {
        assert_eq!(error.name.as_deref(), Some(name), "{label}: error name");
    } else {
        assert_eq!(error.name, None, "{label}: error name absent");
    }
    assert_eq!(
        error.message,
        expected["message"].as_str().unwrap_or_default(),
        "{label}: message"
    );
    if let Some(stack) = expected.get("stack").and_then(Value::as_str) {
        assert_eq!(error.stack.as_deref(), Some(stack), "{label}: stack");
    }
}

/// Replays one captured Part A scenario through the Rust sandbox.
async fn replay(scenario: &Value) {
    let name = scenario["name"]
        .as_str()
        .expect("scenario name")
        .to_string();
    let input = &scenario["input"];
    let sandbox = capture_sandbox(
        // The capture constructs the sandbox with `timeoutMs ?? Infinity`;
        // [`NO_TIMEOUT`] is the port's `Infinity` sentinel.
        input
            .get("timeoutMs")
            .and_then(Value::as_u64)
            .or(Some(crate::codemode::NO_TIMEOUT)),
        input
            .get("memoryLimitBytes")
            .and_then(Value::as_u64)
            .map(|value| value as usize)
            .or(Some(256 * 1024 * 1024)),
    );
    let mut options = CodemodeExecuteOptions::default();
    if let Some(store) = input.get("store").and_then(Value::as_object) {
        for (key, value) in store {
            options.store.insert(key.clone(), value.clone());
        }
    }
    let result = sandbox
        .execute(input["code"].as_str().expect("scenario code"), options)
        .await
        .expect("sandbox not closed");
    let label = name.as_str();

    // `ok` and value (canonical JSON: the capture's `valueJson` re-parsed).
    assert_eq!(
        result.is_ok(),
        scenario["ok"].as_bool().unwrap(),
        "{label}: ok flag"
    );
    if let Some(expected_json) = scenario.get("valueJson").and_then(Value::as_str) {
        let expected: Value =
            serde_json::from_str(expected_json).expect("captured valueJson parses");
        let CodemodeResult::Ok { value, .. } = &result else {
            panic!("{label}: expected an ok result");
        };
        assert_eq!(
            value.clone().expect("non-undefined value"),
            expected,
            "{label}: value mismatch"
        );
    }

    assert_output(label, result.output(), &scenario["output"]);
    assert_calls(label, result.calls(), &scenario["calls"]);
    let error = scenario.get("error").filter(|error| !error.is_null());
    if let Some(error) = error {
        if name == "memory_limit" {
            // Engine divergence (disclosed on the sandbox): when the memory
            // limit is hit, quickjs-ng throws `InternalError: out of memory`
            // — but building that error object allocates, and under
            // exhaustion it fails too, so the engine throws JS_NULL
            // (`JS_ThrowOutOfMemory` → `JS_MakeError` → JS_NULL fallback).
            // Which shape appears is allocation-layout dependent; the native
            // port observed the `{ message: "null" }` degenerate shape where
            // the wasm build observed the InternalError shape. Kind is
            // pinned; name/message/stack are classified instead.
            let CodemodeResult::Err { error: actual, .. } = &result else {
                panic!("{label}: expected a failed execution");
            };
            assert_eq!(
                actual.kind,
                serde_json::from_value::<crate::codemode::types::CodemodeErrorKind>(
                    error["kind"].clone()
                )
                .unwrap(),
                "{label}: error kind"
            );
            assert!(
                actual.message.contains("out of memory") || actual.message == "null",
                "{label}: {:?}",
                actual
            );
        } else {
            assert_error(label, &result, error);
        }
    } else if let CodemodeResult::Err { error, .. } = &result {
        panic!("{label}: unexpected failure {error:?}");
    }

    // Store writes (only successful executions report them).
    if let CodemodeResult::Ok { store_writes, .. } = &result {
        let expected = scenario
            .get("storeWrites")
            .filter(|writes| !writes.is_null())
            .cloned()
            .unwrap_or_else(|| json!({ "set": {}, "delete": [] }));
        let actual = serde_json::to_value(store_writes).expect("store writes serialize");
        assert_eq!(actual, expected, "{label}: store writes");
    }
}

macro_rules! oracle_replay {
    ($scenario:ident) => {
        #[tokio::test(flavor = "multi_thread")]
        async fn $scenario() {
            let oracle = oracle();
            let scenario = oracle["partA"]
                .as_array()
                .expect("partA array")
                .into_iter()
                .find(|scenario| scenario["name"].as_str() == Some(stringify!($scenario)))
                .unwrap_or_else(|| {
                    panic!(
                        "scenario {} missing from the capture",
                        stringify!($scenario)
                    )
                });
            replay(scenario).await;
        }
    };
}

oracle_replay!(simple_call);
oracle_replay!(await_all_and_echo);
oracle_replay!(console_and_text);
oracle_replay!(all_tools_metadata);
oracle_replay!(globals_and_namespaces);
oracle_replay!(tool_error_script);
oracle_replay!(tool_error_non_error_throw);
oracle_replay!(unknown_tool);
oracle_replay!(store_load_roundtrip);
oracle_replay!(store_value_over_limit);
oracle_replay!(parse_error);
oracle_replay!(runtime_type_error);
oracle_replay!(stalled_script);
oracle_replay!(exit_early);
oracle_replay!(exit_with_value);
oracle_replay!(unawaited_call_cancelled);
oracle_replay!(timeout_loop);
oracle_replay!(json_number_formatting);
oracle_replay!(bigint_text_fails);
oracle_replay!(throw_non_error_value);
oracle_replay!(deep_recursion_range_error);
oracle_replay!(memory_limit);
oracle_replay!(nested_promises_and_catch);

/// Every captured Part A scenario is replayed by the macros above, and the
/// capture pinned every call name to the sandbox tool table.
#[test]
fn oracle_covers_every_captured_scenario() {
    let oracle = oracle();
    let scenarios = oracle["partA"].as_array().expect("partA");
    assert_eq!(scenarios.len(), 23, "captured execution scenarios");
    assert_eq!(oracle["partC"].as_object().unwrap().len(), 18);
    assert_eq!(oracle["partB"].as_object().unwrap().len(), 11);
    for scenario in scenarios {
        assert!(
            scenario["input"]["code"].is_string(),
            "scenario {} carries its input script",
            scenario["name"].as_str().unwrap()
        );
        assert_eq!(
            scenario["callNamesPinned"].as_bool(),
            Some(true),
            "call names pinned to the tool table"
        );
    }
}

// ---------------------------------------------------------------------------
// Part B: the extension description pipeline
// ---------------------------------------------------------------------------

/// The capture's extension tool set as upstream `AgentTool` JSON
/// (`partB.extension_tools_json`): `outputSchema` present only where the tool
/// declared one. `to_declarable` mirrors upstream `toCodemodeDeclaration`
/// (`outputSchema ?? TEXT_OUTPUT_SCHEMA`).
fn capture_extension_declarables() -> Vec<Declarable> {
    let oracle = oracle();
    let tools = oracle["partB"]["extension_tools_json"]
        .as_array()
        .expect("extension tools")
        .clone();
    tools.iter().map(to_declarable).collect()
}

fn to_declarable(tool: &Value) -> Declarable {
    Declarable {
        name: tool["name"].as_str().expect("tool name").to_string(),
        description: tool["description"].as_str().map(str::to_string),
        input_schema: Some(tool["parameters"].clone()),
        output_schema: Some(
            tool.get("outputSchema")
                .cloned()
                .unwrap_or_else(|| json!({ "type": "string" })),
        ),
        spread: false,
        signature: None,
    }
}

fn description_options(
    options: &Value,
) -> crate::coding_agent::extensions::codemode::tool::CodemodeDescriptionOptions {
    let namespaces: BTreeMap<String, crate::coding_agent::extensions::types::ToolNamespace> =
        options
            .get("namespaces")
            .and_then(Value::as_object)
            .map(|map| {
                map.iter()
                    .map(|(name, namespace)| {
                        (
                            name.clone(),
                            serde_json::from_value(namespace.clone()).expect("namespace"),
                        )
                    })
                    .collect()
            })
            .unwrap_or_default();
    let deferred: std::collections::BTreeSet<String> = options
        .get("deferred")
        .and_then(Value::as_array)
        .map(|values| {
            values
                .iter()
                .map(|value| value.as_str().expect("tool name").to_string())
                .collect()
        })
        .unwrap_or_default();
    crate::coding_agent::extensions::codemode::tool::CodemodeDescriptionOptions {
        models: options
            .get("models")
            .and_then(Value::as_bool)
            .unwrap_or(false),
        namespaces,
        deferred,
        inline_budget: options
            .get("inlineBudget")
            .and_then(Value::as_u64)
            .map(|value| value as usize),
    }
}

#[test]
fn extension_descriptions_match_upstream() {
    let oracle = oracle();
    let part_b = &oracle["partB"];
    let tools = capture_extension_declarables();
    let codemode =
        crate::coding_agent::extensions::codemode::tool::create_codemode_description_for_declarations;

    for key in [
        "empty",
        "models_only",
        "full",
        "no_namespaces",
        "deferred",
        "budget_tight",
        "budget_partial",
    ] {
        // `empty` and `models_only` were captured with no tools.
        let tools = match key {
            "empty" | "models_only" => Vec::new(),
            _ => tools.clone(),
        };
        let expected = part_b[key]["description"].as_str().unwrap();
        let actual = codemode(&tools, &description_options(&part_b[key]["options"]));
        assert_eq!(actual, expected, "description `{key}` mismatch");
    }

    // Per-tool samples (`renderToolSample(toCodemodeDeclaration(tool))`).
    let samples = part_b["samples"].as_object().expect("pinned samples");
    for (name, expected) in samples {
        let tool = tools
            .iter()
            .find(|tool| &tool.name == name)
            .unwrap_or_else(|| panic!("sample tool {name}"));
        assert_eq!(
            render_tool_sample(tool, None),
            expected.as_str().unwrap(),
            "sample `{name}` mismatch"
        );
    }
}

/// The `codemode` tool's parameter schema (upstream TypeBox `codemodeSchema`,
/// pinned as JSON) and the model-global declarations.
#[test]
fn codemode_schema_and_model_declarations_match_upstream() {
    let oracle = oracle();
    let part_b = &oracle["partB"];
    assert_eq!(
        serde_json::to_value(crate::coding_agent::extensions::codemode::tool::codemode_schema())
            .unwrap(),
        serde_json::from_str::<Value>(part_b["codemode_schema_json"].as_str().unwrap()).unwrap(),
        "codemodeSchema mismatch"
    );
    // MODEL_GLOBAL_DECLARATIONS at the JSON seam (upstream JSON.stringify
    // drops the undefined members).
    let actual: Vec<Value> =
        crate::coding_agent::extensions::codemode::tool::model_global_declarations()
            .iter()
            .map(|declaration| {
                let mut object = serde_json::Map::new();
                object.insert("name".to_string(), json!(declaration.name));
                if let Some(description) = &declaration.description {
                    object.insert("description".to_string(), json!(description));
                }
                if let Some(signature) = &declaration.signature {
                    object.insert("signature".to_string(), json!(signature));
                }
                Value::Object(object)
            })
            .collect();
    assert_eq!(
        Value::Array(actual),
        serde_json::from_str::<Value>(part_b["model_global_declarations_json"].as_str().unwrap())
            .unwrap(),
        "MODEL_GLOBAL_DECLARATIONS mismatch"
    );
}

// ---------------------------------------------------------------------------
// Part C: parseCodemodeSource
// ---------------------------------------------------------------------------

#[test]
fn source_parsing_matches_upstream() {
    let oracle = oracle();
    for (key, case) in oracle["partC"].as_object().expect("partC") {
        let input = source_scenario_input(key);
        match parse_codemode_source(&input) {
            Ok(parsed) => {
                assert!(case["ok"].as_bool().unwrap(), "{key}: expected failure");
                assert_eq!(parsed.code, case["code"].as_str().unwrap(), "{key}: code");
                let expected_options = &case["options"];
                assert_eq!(
                    parsed.options.max_output_tokens,
                    expected_options
                        .get("maxOutputTokens")
                        .and_then(Value::as_f64),
                    "{key}"
                );
                assert_eq!(
                    parsed.options.timeout_ms,
                    expected_options.get("timeoutMs").and_then(Value::as_u64),
                    "{key}"
                );
            }
            Err(error) => {
                assert!(!case["ok"].as_bool().unwrap(), "{key}: expected success");
                assert_eq!(
                    case["isCodemodeSourceError"].as_bool(),
                    Some(true),
                    "{key}: capture marks the error kind"
                );
                let expected_message = case["message"].as_str().unwrap();
                if key == "invalid_json" {
                    // V8 `JSON.parse` message text upstream; serde_json here.
                    // Classified: same head, parser-specific suffix.
                    let head = "@options must be valid JSON with supported fields `max_output_tokens` and `timeout_ms`: ";
                    assert!(error.0.starts_with(head), "{key}: {error:?}");
                    assert_ne!(error.0, format!("{head}{expected_message}"));
                } else {
                    assert_eq!(error.0, expected_message, "{key}: message");
                }
            }
        }
    }
}

/// The exact inputs of the capture's Part C (mirrors capture_codemode_oracle.mjs).
fn source_scenario_input(key: &str) -> String {
    match key {
        "plain" => "return 1;\n".to_string(),
        "options" => "// @options: {\"max_output_tokens\": 2000, \"timeout_ms\": 30000}\nreturn 1;"
            .to_string(),
        "options_no_space" => "// @options:{\"timeout_ms\": 5}\nreturn 1;".to_string(),
        "options_indent" => "  // @options: {\"max_output_tokens\": 0}\nreturn 1;".to_string(),
        "empty_input" => "   \n".to_string(),
        "only_options" => "// @options: {\"max_output_tokens\": 100}".to_string(),
        "options_with_body_whitespace" => "// @options: {}\n   \n".to_string(),
        "unknown_field" => "// @options: {\"nope\": 1}\nreturn 1;".to_string(),
        "zero_timeout" => "// @options: {\"timeout_ms\": 0}\nreturn 1;".to_string(),
        "huge_timeout" => "// @options: {\"timeout_ms\": 2147483648}\nreturn 1;".to_string(),
        "boundary_timeout" => "// @options: {\"timeout_ms\": 2147483647}\nreturn 1;".to_string(),
        "negative_tokens" => "// @options: {\"max_output_tokens\": -1}\nreturn 1;".to_string(),
        "float_tokens" => "// @options: {\"max_output_tokens\": 1.5}\nreturn 1;".to_string(),
        "array_options" => "// @options: [1]\nreturn 1;".to_string(),
        "invalid_json" => "// @options: {bad json}\nreturn 1;".to_string(),
        "crlf_first_line" => "// @options: {\"max_output_tokens\": 7}\r\nreturn 1;".to_string(),
        "no_newline_after_prefix" => "// @options:".to_string(),
        "non_object_tokens" => "// @options: \"text\"\nreturn 1;".to_string(),
        other => panic!("unhandled source scenario {other}"),
    }
}
