// Generates Rust constant blocks from oracle_output.json for
// src/tui/main_screen_oracle_consts.rs (mounted from main_screen_tests.rs).
// Byte arrays use Rust string escaping; structured values are canonical JSON
// (recursively key-sorted). Modeled on scratch/tui_oracle/gen_data.mjs.
import fs from "node:fs";

const o = JSON.parse(fs.readFileSync(new URL("./oracle_output.json", import.meta.url), "utf8"));

function esc(s) {
	let out = "";
	for (const ch of String(s)) {
		const c = ch.codePointAt(0);
		if (ch === "\\") out += "\\\\";
		else if (ch === '"') out += '\\"';
		else if (ch === "\n") out += "\\n";
		else if (ch === "\r") out += "\\r";
		else if (ch === "\t") out += "\\t";
		else if (c < 0x20 || c === 0x7f) out += `\\u{${c.toString(16)}}`;
		else out += ch;
	}
	return `"${out}"`;
}

function canonical(v) {
	if (Array.isArray(v)) return v.map(canonical);
	if (v && typeof v === "object") {
		const sorted = {};
		for (const k of Object.keys(v).sort()) sorted[k] = canonical(v[k]);
		return sorted;
	}
	return v;
}
const json = (v) => JSON.stringify(canonical(v));

const L = [];
const w = (s) => L.push(s);
const writes = (name, arr) => w(`pub const ${name}: &[&str] = &[${arr.map(esc).join(", ")}];`);
const raw = (name, s) => w(`pub const ${name}: &str = ${esc(s)};`);
const jstr = (name, v) => w(`pub const ${name}: &str = ${esc(json(v))};`);
const num = (name, v) => w(`pub const ${name}: usize = ${v};`);

w("// Generated by scratch/main_screen_oracle/gen_consts.mjs from oracle_output.json — do not edit by hand.");
w("// Every value was captured by running the actual upstream tui-main-screen.ts");
w("// (TuiMainScreen over the real TuiBase) under node --experimental-strip-types;");
w("// byte arrays are FakeTerminal write boundaries (one entry per terminal.write call).");
w("");

writes("SPINNER_FRAME_0_WRITES", o.spinner_frames.frames[0]);
writes("SPINNER_FRAME_1_WRITES", o.spinner_frames.frames[1]);
writes("SPINNER_FRAME_2_WRITES", o.spinner_frames.frames[2]);
writes("SPINNER_FRAME_3_WRITES", o.spinner_frames.frames[3]);
writes("NO_CHANGE_WRITES", o.no_change_writes);
writes("FIRST_RENDER_WRITES", o.first_render.writes);
num("FIRST_RENDER_FULL_REDRAWS", o.first_render.fullRedraws);
writes("STOP_DEFAULT_WRITES", o.stop_default_writes);
writes("RENDER_AFTER_STOP_WRITES", o.render_after_stop_writes);
writes("STOP_PRESERVE_SCREEN_WRITES", o.stop_preserve_screen_writes);
writes("NONADJACENT_CHANGE_WRITES", o.nonadjacent_change_writes);
writes("APPEND_LINES_WRITES", o.append_lines_writes);
writes("DELETE_TAIL_LINES_WRITES", o.delete_tail_lines_writes);
writes("SHRINK_THEN_CHANGE_WRITES", o.shrink_then_change_writes);
writes("FIRST_LINE_CHANGE_WRITES", o.first_line_change_writes);
writes("APPEND_AFTER_CHANGE_WRITES", o.append_after_change_writes);
writes("LAST_LINE_CHANGE_WRITES", o.last_line_change_writes);
writes("SHRINK_TO_EMPTY_WRITES", o.shrink_to_empty_writes);
writes("REGROW_AFTER_EMPTY_WRITES", o.regrow_after_empty_writes);
writes("CLEAR_ON_SHRINK_WRITES", o.clear_on_shrink_writes);
num("CLEAR_ON_SHRINK_DELTA", o.clear_on_shrink_delta);
writes("CLEAR_ON_SHRINK_SINGLE_WRITES", o.clear_on_shrink_single_writes);
writes("CLEAR_ON_SHRINK_EMPTY_WRITES", o.clear_on_shrink_empty_writes);
writes("CLEAR_CHILDREN_WRITES", o.clear_children_writes);
writes("DELETED_VIEWPORT_UP_WRITES", o.deleted_viewport_up_writes);
num("DELETED_VIEWPORT_UP_DELTA", o.deleted_viewport_up_delta);
writes("APPEND_AFTER_VIEWPORT_RESET_WRITES", o.append_after_viewport_reset_writes);
num("APPEND_AFTER_VIEWPORT_RESET_DELTA", o.append_after_viewport_reset_delta);
writes("TRANSIENT_INFLATION_WRITES", o.transient_inflation_writes);
num("TRANSIENT_INFLATION_DELTA", o.transient_inflation_delta);
writes("RESIZE_WIDTH_WRITES", o.resize_width_writes);
num("RESIZE_WIDTH_DELTA", o.resize_width_delta);
writes("RESIZE_HEIGHT_WRITES", o.resize_height_writes);
num("RESIZE_HEIGHT_DELTA", o.resize_height_delta);
writes("TERMUX_RESIZE_FRAME_0_WRITES", o.termux_resize_frames.frames[0]);
writes("TERMUX_RESIZE_FRAME_1_WRITES", o.termux_resize_frames.frames[1]);
writes("TERMUX_RESIZE_FRAME_2_WRITES", o.termux_resize_frames.frames[2]);
writes("TERMUX_RESIZE_FRAME_3_WRITES", o.termux_resize_frames.frames[3]);
num("TERMUX_RESIZE_DELTA", o.termux_resize_delta);
writes("CURSOR_MARKER_MOVED_WRITES", o.cursor_marker_moved_writes);
writes("CURSOR_MARKER_VISIBLE_WRITES", o.cursor_marker_visible_writes);
writes("STYLES_RESET_WRITES", o.styles_reset_writes);
jstr("KEYBOARD_PREEMPT", o.keyboard_preempt);
jstr("BOUNDED_FULL", o.bounded_full);
jstr("BOUNDED_DIFF", o.bounded_diff);
writes("KITTY_RESERVED_ROWS_DIFF_WRITES", o.kitty_reserved_rows_diff.writes);
writes("KITTY_PRECLEAR_SCROLL_WRITES", o.kitty_preclear_scroll.writes);
num("KITTY_PRECLEAR_SCROLL_DELTA", o.kitty_preclear_scroll.delta);
writes("KITTY_FULLREDRAW_RESERVED_WRITES", o.kitty_fullredraw_reserved.writes);
num("KITTY_FULLREDRAW_RESERVED_DELTA", o.kitty_fullredraw_reserved.delta);
writes("KITTY_TALLER_THAN_VIEWPORT_WRITES", o.kitty_taller_than_viewport.writes);
jstr("KITTY_TALLER_HAS_CURSOR_UP_PREFIX", { value: o.kitty_taller_than_viewport.hasCursorUpPrefix });
raw("KITTY_DELETE_CHANGED_JOINED", o.kitty_delete_changed.writes);
jstr("KITTY_DELETE_CHANGED_META", {
	deleteIndex: o.kitty_delete_changed.deleteIndex,
	drawIndex: o.kitty_delete_changed.drawIndex,
	deleteBeforeDraw: o.kitty_delete_changed.deleteBeforeDraw,
});
raw("KITTY_RESERVED_ROW_CHANGE_JOINED", o.kitty_reserved_row_change.writes);
jstr("KITTY_RESERVED_ROW_CHANGE_META", {
	deleteIndex: o.kitty_reserved_row_change.deleteIndex,
	drawIndex: o.kitty_reserved_row_change.drawIndex,
	deleteBeforeDraw: o.kitty_reserved_row_change.deleteBeforeDraw,
	hasFullClear: o.kitty_reserved_row_change.hasFullClear,
});
raw("KITTY_FULLREDRAW_DELETES_PREVIOUS_JOINED", o.kitty_fullredraw_deletes_previous.writes);
jstr("KITTY_FULLREDRAW_DELETES_PREVIOUS_META", {
	deleteBeforeClear: o.kitty_fullredraw_deletes_previous.deleteBeforeClear,
	deleteIndex: o.kitty_fullredraw_deletes_previous.deleteIndex,
	clearIndex: o.kitty_fullredraw_deletes_previous.clearIndex,
});
raw("CRASH_DUMP_LOGDIR_MESSAGE", o.crash_dump_logdir.message);
raw("CRASH_DUMP_LOGDIR_TEXT", o.crash_dump_logdir.crashText);
writes("CRASH_DUMP_LOGDIR_STOP_WRITES", o.crash_dump_logdir.stopWrites);
raw("CRASH_DUMP_TMPDIR_MESSAGE", o.crash_dump_tmpdir.message);
raw("CRASH_DUMP_TMPDIR_TEXT", o.crash_dump_tmpdir.crashText);
raw("DEBUG_REDRAW_LOG_TEXT", o.debug_redraw_log.logText);
raw("PI_TUI_DEBUG_DUMP_CONTENT", o.pi_tui_debug_dump.content);
writes("RESTORE_RENDER_STATE_WRITES", o.restore_render_state.writes);
writes("RESTORE_RENDER_STATE_IMAGES_WRITES", o.restore_render_state_images.writes);
jstr("RENDER_STATE_SHAPE", o.render_state_shape);

fs.writeFileSync(
	new URL("../../src/tui/main_screen_oracle_consts.rs", import.meta.url),
	L.join("\n") + "\n",
);
console.log("consts written:", L.length, "lines");
