// @generated by docs/migration/reference/latex/run.mjs; do not edit.
// Upstream pi/packages/tui/src/latex.ts SHA-256: 6488a1d90ee99ca8f59855e6a38c45fa6b750f835dd1e95d086b4742af8f8cba

pub(super) fn symbols(value: &str) -> Option<&'static str> {
    match value {
        "alpha" => Some("α"),
        "beta" => Some("β"),
        "gamma" => Some("γ"),
        "delta" => Some("δ"),
        "epsilon" => Some("ϵ"),
        "varepsilon" => Some("ε"),
        "zeta" => Some("ζ"),
        "eta" => Some("η"),
        "theta" => Some("θ"),
        "vartheta" => Some("ϑ"),
        "iota" => Some("ι"),
        "kappa" => Some("κ"),
        "varkappa" => Some("ϰ"),
        "lambda" => Some("λ"),
        "mu" => Some("μ"),
        "nu" => Some("ν"),
        "xi" => Some("ξ"),
        "pi" => Some("π"),
        "varpi" => Some("ϖ"),
        "rho" => Some("ρ"),
        "varrho" => Some("ϱ"),
        "sigma" => Some("σ"),
        "varsigma" => Some("ς"),
        "tau" => Some("τ"),
        "upsilon" => Some("υ"),
        "phi" => Some("ϕ"),
        "varphi" => Some("φ"),
        "chi" => Some("χ"),
        "psi" => Some("ψ"),
        "omega" => Some("ω"),
        "Gamma" => Some("Γ"),
        "Delta" => Some("Δ"),
        "Theta" => Some("Θ"),
        "Lambda" => Some("Λ"),
        "Xi" => Some("Ξ"),
        "Pi" => Some("Π"),
        "Sigma" => Some("Σ"),
        "Upsilon" => Some("Υ"),
        "Phi" => Some("Φ"),
        "Psi" => Some("Ψ"),
        "Omega" => Some("Ω"),
        "pm" => Some("±"),
        "mp" => Some("∓"),
        "times" => Some("×"),
        "div" => Some("÷"),
        "cdot" => Some("·"),
        "ast" => Some("∗"),
        "star" => Some("⋆"),
        "circ" => Some("∘"),
        "bullet" => Some("•"),
        "oplus" => Some("⊕"),
        "ominus" => Some("⊖"),
        "otimes" => Some("⊗"),
        "oslash" => Some("⊘"),
        "odot" => Some("⊙"),
        "bigcirc" => Some("○"),
        "dagger" => Some("†"),
        "ddagger" => Some("‡"),
        "amalg" => Some("⨿"),
        "uplus" => Some("⊎"),
        "sqcap" => Some("⊓"),
        "sqcup" => Some("⊔"),
        "bowtie" => Some("⋈"),
        "Join" => Some("⋈"),
        "ltimes" => Some("⋉"),
        "rtimes" => Some("⋊"),
        "leftouterjoin" => Some("⟕"),
        "rightouterjoin" => Some("⟖"),
        "fullouterjoin" => Some("⟗"),
        "triangleleft" => Some("◁"),
        "triangleright" => Some("▷"),
        "wr" => Some("≀"),
        "cap" => Some("∩"),
        "cup" => Some("∪"),
        "bigcap" => Some("⋂"),
        "bigcup" => Some("⋃"),
        "bigwedge" => Some("⋀"),
        "bigvee" => Some("⋁"),
        "bigsqcup" => Some("⨆"),
        "biguplus" => Some("⨄"),
        "bigoplus" => Some("⨁"),
        "bigotimes" => Some("⨂"),
        "bigodot" => Some("⨀"),
        "setminus" => Some("∖"),
        "in" => Some("∈"),
        "notin" => Some("∉"),
        "ni" => Some("∋"),
        "subset" => Some("⊂"),
        "supset" => Some("⊃"),
        "subseteq" => Some("⊆"),
        "supseteq" => Some("⊇"),
        "sqsubset" => Some("⊏"),
        "sqsupset" => Some("⊐"),
        "sqsubseteq" => Some("⊑"),
        "sqsupseteq" => Some("⊒"),
        "prec" => Some("≺"),
        "preceq" => Some("≼"),
        "succ" => Some("≻"),
        "succeq" => Some("≽"),
        "ll" => Some("≪"),
        "gg" => Some("≫"),
        "le" => Some("≤"),
        "leq" => Some("≤"),
        "leqslant" => Some("≤"),
        "ge" => Some("≥"),
        "geq" => Some("≥"),
        "geqslant" => Some("≥"),
        "ne" => Some("≠"),
        "neq" => Some("≠"),
        "equiv" => Some("≡"),
        "approx" => Some("≈"),
        "sim" => Some("∼"),
        "simeq" => Some("≃"),
        "cong" => Some("≅"),
        "asymp" => Some("≍"),
        "doteq" => Some("≐"),
        "propto" => Some("∝"),
        "parallel" => Some("∥"),
        "perp" => Some("⊥"),
        "mid" => Some("∣"),
        "vdash" => Some("⊢"),
        "dashv" => Some("⊣"),
        "models" => Some("⊨"),
        "Vdash" => Some("⊩"),
        "Vvdash" => Some("⊪"),
        "nvdash" => Some("⊬"),
        "nvDash" => Some("⊭"),
        "forall" => Some("∀"),
        "exists" => Some("∃"),
        "nexists" => Some("∄"),
        "neg" => Some("¬"),
        "land" => Some("∧"),
        "wedge" => Some("∧"),
        "lor" => Some("∨"),
        "vee" => Some("∨"),
        "to" => Some("→"),
        "rightarrow" => Some("→"),
        "longrightarrow" => Some("→"),
        "leftarrow" => Some("←"),
        "longleftarrow" => Some("←"),
        "gets" => Some("←"),
        "leftrightarrow" => Some("↔"),
        "longleftrightarrow" => Some("↔"),
        "hookleftarrow" => Some("↩"),
        "hookrightarrow" => Some("↪"),
        "twoheadleftarrow" => Some("↞"),
        "twoheadrightarrow" => Some("↠"),
        "leftharpoonup" => Some("↼"),
        "leftharpoondown" => Some("↽"),
        "rightharpoonup" => Some("⇀"),
        "rightharpoondown" => Some("⇁"),
        "rightleftharpoons" => Some("⇌"),
        "leftrightharpoons" => Some("⇋"),
        "nearrow" => Some("↗"),
        "searrow" => Some("↘"),
        "swarrow" => Some("↙"),
        "nwarrow" => Some("↖"),
        "rightsquigarrow" => Some("⇝"),
        "leadsto" => Some("⇝"),
        "Rightarrow" => Some("⇒"),
        "Longrightarrow" => Some("⇒"),
        "Leftarrow" => Some("⇐"),
        "Longleftarrow" => Some("⇐"),
        "Leftrightarrow" => Some("⇔"),
        "Longleftrightarrow" => Some("⇔"),
        "implies" => Some("⇒"),
        "iff" => Some("⇔"),
        "mapsto" => Some("↦"),
        "longmapsto" => Some("↦"),
        "uparrow" => Some("↑"),
        "downarrow" => Some("↓"),
        "partial" => Some("∂"),
        "nabla" => Some("∇"),
        "int" => Some("∫"),
        "iint" => Some("∬"),
        "iiint" => Some("∭"),
        "oint" => Some("∮"),
        "sum" => Some("∑"),
        "prod" => Some("∏"),
        "coprod" => Some("∐"),
        "infty" => Some("∞"),
        "emptyset" => Some("∅"),
        "varnothing" => Some("∅"),
        "angle" => Some("∠"),
        "therefore" => Some("∴"),
        "because" => Some("∵"),
        "aleph" => Some("ℵ"),
        "beth" => Some("ℶ"),
        "gimel" => Some("ℷ"),
        "daleth" => Some("ℸ"),
        "top" => Some("⊤"),
        "bot" => Some("⊥"),
        "triangle" => Some("△"),
        "square" => Some("□"),
        "lozenge" => Some("◊"),
        "checkmark" => Some("✓"),
        "complement" => Some("∁"),
        "wp" => Some("℘"),
        "prime" => Some("′"),
        "ldots" => Some("…"),
        "dots" => Some("…"),
        "cdots" => Some("⋯"),
        "vdots" => Some("⋮"),
        "ddots" => Some("⋱"),
        "ell" => Some("ℓ"),
        "hbar" => Some("ℏ"),
        "Im" => Some("ℑ"),
        "Re" => Some("ℜ"),
        "langle" => Some("⟨"),
        "rangle" => Some("⟩"),
        "vert" => Some("|"),
        "lvert" => Some("|"),
        "rvert" => Some("|"),
        "Vert" => Some("‖"),
        "lVert" => Some("‖"),
        "rVert" => Some("‖"),
        "lbrace" => Some("{"),
        "rbrace" => Some("}"),
        "backslash" => Some("\\"),
        "lfloor" => Some("⌊"),
        "rfloor" => Some("⌋"),
        "lceil" => Some("⌈"),
        "rceil" => Some("⌉"),
        "colon" => Some(":"),
        _ => None,
    }
}

pub(super) fn negated_symbols(value: &str) -> Option<&'static str> {
    match value {
        "<" => Some("≮"),
        ">" => Some("≯"),
        "=" => Some("≠"),
        "∈" => Some("∉"),
        "∋" => Some("∌"),
        "∣" => Some("∤"),
        "∥" => Some("∦"),
        "∼" => Some("≁"),
        "≃" => Some("≄"),
        "≅" => Some("≇"),
        "≈" => Some("≉"),
        "≡" => Some("≢"),
        "≤" => Some("≰"),
        "≥" => Some("≱"),
        "≺" => Some("⊀"),
        "≻" => Some("⊁"),
        "⊂" => Some("⊄"),
        "⊃" => Some("⊅"),
        "⊆" => Some("⊈"),
        "⊇" => Some("⊉"),
        "⊢" => Some("⊬"),
        "⊨" => Some("⊭"),
        "↔" => Some("↮"),
        "←" => Some("↚"),
        "→" => Some("↛"),
        "⇒" => Some("⇏"),
        "⇐" => Some("⇍"),
        "⇔" => Some("⇎"),
        "≼" => Some("⋠"),
        "≽" => Some("⋡"),
        _ => None,
    }
}

pub(super) fn blackboard(value: &str) -> Option<&'static str> {
    match value {
        "C" => Some("ℂ"),
        "H" => Some("ℍ"),
        "N" => Some("ℕ"),
        "P" => Some("ℙ"),
        "Q" => Some("ℚ"),
        "R" => Some("ℝ"),
        "Z" => Some("ℤ"),
        _ => None,
    }
}

pub(super) fn superscripts(value: &str) -> Option<&'static str> {
    match value {
        "0" => Some("⁰"),
        "1" => Some("¹"),
        "2" => Some("²"),
        "3" => Some("³"),
        "4" => Some("⁴"),
        "5" => Some("⁵"),
        "6" => Some("⁶"),
        "7" => Some("⁷"),
        "8" => Some("⁸"),
        "9" => Some("⁹"),
        "+" => Some("⁺"),
        "-" => Some("⁻"),
        "=" => Some("⁼"),
        "(" => Some("⁽"),
        ")" => Some("⁾"),
        "a" => Some("ᵃ"),
        "b" => Some("ᵇ"),
        "c" => Some("ᶜ"),
        "d" => Some("ᵈ"),
        "e" => Some("ᵉ"),
        "f" => Some("ᶠ"),
        "g" => Some("ᵍ"),
        "h" => Some("ʰ"),
        "i" => Some("ⁱ"),
        "j" => Some("ʲ"),
        "k" => Some("ᵏ"),
        "l" => Some("ˡ"),
        "m" => Some("ᵐ"),
        "n" => Some("ⁿ"),
        "o" => Some("ᵒ"),
        "p" => Some("ᵖ"),
        "r" => Some("ʳ"),
        "s" => Some("ˢ"),
        "t" => Some("ᵗ"),
        "u" => Some("ᵘ"),
        "v" => Some("ᵛ"),
        "w" => Some("ʷ"),
        "x" => Some("ˣ"),
        "y" => Some("ʸ"),
        "z" => Some("ᶻ"),
        _ => None,
    }
}

pub(super) fn subscripts(value: &str) -> Option<&'static str> {
    match value {
        "0" => Some("₀"),
        "1" => Some("₁"),
        "2" => Some("₂"),
        "3" => Some("₃"),
        "4" => Some("₄"),
        "5" => Some("₅"),
        "6" => Some("₆"),
        "7" => Some("₇"),
        "8" => Some("₈"),
        "9" => Some("₉"),
        "+" => Some("₊"),
        "-" => Some("₋"),
        "=" => Some("₌"),
        "(" => Some("₍"),
        ")" => Some("₎"),
        "a" => Some("ₐ"),
        "e" => Some("ₑ"),
        "h" => Some("ₕ"),
        "i" => Some("ᵢ"),
        "j" => Some("ⱼ"),
        "k" => Some("ₖ"),
        "l" => Some("ₗ"),
        "m" => Some("ₘ"),
        "n" => Some("ₙ"),
        "o" => Some("ₒ"),
        "p" => Some("ₚ"),
        "r" => Some("ᵣ"),
        "s" => Some("ₛ"),
        "t" => Some("ₜ"),
        "u" => Some("ᵤ"),
        "v" => Some("ᵥ"),
        "x" => Some("ₓ"),
        _ => None,
    }
}

pub(super) fn accents(value: &str) -> Option<&'static str> {
    match value {
        "acute" => Some("́"),
        "bar" => Some("̅"),
        "breve" => Some("̆"),
        "check" => Some("̌"),
        "ddot" => Some("̈"),
        "dot" => Some("̇"),
        "grave" => Some("̀"),
        "hat" => Some("̂"),
        "mathring" => Some("̊"),
        "overleftarrow" => Some("⃖"),
        "overleftrightarrow" => Some("⃡"),
        "overline" => Some("̅"),
        "overrightarrow" => Some("⃗"),
        "tilde" => Some("̃"),
        "underline" => Some("̲"),
        "vec" => Some("⃗"),
        "widehat" => Some("̂"),
        "widetilde" => Some("̃"),
        _ => None,
    }
}

pub(super) fn named_operators(value: &str) -> bool {
    matches!(
        value,
        "arccos"
            | "arcsin"
            | "arctan"
            | "arg"
            | "cos"
            | "cosh"
            | "cot"
            | "coth"
            | "csc"
            | "deg"
            | "det"
            | "dim"
            | "exp"
            | "gcd"
            | "hom"
            | "inf"
            | "ker"
            | "lg"
            | "lim"
            | "liminf"
            | "limsup"
            | "ln"
            | "log"
            | "max"
            | "min"
            | "Pr"
            | "sec"
            | "sin"
            | "sinh"
            | "sup"
            | "tan"
            | "tanh"
    )
}

pub(super) fn limit_operators(value: &str) -> bool {
    matches!(
        value,
        "argmax"
            | "argmin"
            | "inf"
            | "injlim"
            | "lim"
            | "liminf"
            | "limsup"
            | "max"
            | "min"
            | "projlim"
            | "sup"
    )
}

pub(super) fn display_limit_symbols(value: &str) -> bool {
    matches!(
        value,
        "bigcap"
            | "bigcup"
            | "bigodot"
            | "bigoplus"
            | "bigotimes"
            | "bigsqcup"
            | "biguplus"
            | "bigvee"
            | "bigwedge"
            | "coprod"
            | "int"
            | "iint"
            | "iiint"
            | "oint"
            | "prod"
            | "sum"
    )
}

pub(super) fn relation_commands(value: &str) -> bool {
    matches!(
        value,
        "Leftarrow"
            | "Leftrightarrow"
            | "Longleftarrow"
            | "Longleftrightarrow"
            | "Longrightarrow"
            | "Rightarrow"
            | "Join"
            | "Vdash"
            | "Vvdash"
            | "approx"
            | "asymp"
            | "bowtie"
            | "cong"
            | "dashv"
            | "fullouterjoin"
            | "doteq"
            | "downarrow"
            | "equiv"
            | "ge"
            | "geq"
            | "geqslant"
            | "gets"
            | "gg"
            | "hookleftarrow"
            | "hookrightarrow"
            | "iff"
            | "implies"
            | "in"
            | "leadsto"
            | "le"
            | "leftarrow"
            | "leftharpoondown"
            | "leftharpoonup"
            | "leftrightarrow"
            | "leftrightharpoons"
            | "leftouterjoin"
            | "leq"
            | "leqslant"
            | "ll"
            | "longleftarrow"
            | "longleftrightarrow"
            | "longmapsto"
            | "longrightarrow"
            | "ltimes"
            | "mapsto"
            | "mid"
            | "models"
            | "ne"
            | "nearrow"
            | "neq"
            | "ni"
            | "notin"
            | "nvdash"
            | "nvDash"
            | "nwarrow"
            | "parallel"
            | "perp"
            | "prec"
            | "preceq"
            | "propto"
            | "rightharpoondown"
            | "rightharpoonup"
            | "rightleftharpoons"
            | "rightouterjoin"
            | "rightarrow"
            | "rightsquigarrow"
            | "rtimes"
            | "searrow"
            | "sim"
            | "simeq"
            | "sqsubset"
            | "sqsubseteq"
            | "sqsupset"
            | "sqsupseteq"
            | "subset"
            | "subseteq"
            | "succ"
            | "succeq"
            | "supset"
            | "supseteq"
            | "swarrow"
            | "to"
            | "triangleleft"
            | "triangleright"
            | "twoheadleftarrow"
            | "twoheadrightarrow"
            | "uparrow"
            | "vdash"
    )
}

pub(super) fn spacing_commands(value: &str) -> bool {
    matches!(
        value,
        "," | ":"
            | ";"
            | " "
            | ">"
            | "enspace"
            | "enskip"
            | "medspace"
            | "quad"
            | "qquad"
            | "thickspace"
            | "thinspace"
    )
}

pub(super) fn negative_spacing_commands(value: &str) -> bool {
    matches!(
        value,
        "!" | "negmedspace" | "negthickspace" | "negthinspace"
    )
}

pub(super) fn ignored_commands(value: &str) -> bool {
    matches!(
        value,
        "displaystyle" | "limits" | "nolimits" | "scriptstyle" | "scriptscriptstyle" | "textstyle"
    )
}

pub(super) fn size_commands(value: &str) -> bool {
    matches!(
        value,
        "big"
            | "Big"
            | "bigg"
            | "Bigg"
            | "bigl"
            | "Bigl"
            | "biggl"
            | "Biggl"
            | "bigr"
            | "Bigr"
            | "biggr"
            | "Biggr"
    )
}

pub(super) fn plain_wrappers(value: &str) -> bool {
    matches!(
        value,
        "emph"
            | "mathcal"
            | "mathbf"
            | "mathfrak"
            | "mathit"
            | "mathrm"
            | "mathnormal"
            | "mathscr"
            | "mathsf"
            | "mathtt"
            | "mathup"
            | "mbox"
            | "overbrace"
            | "pmb"
            | "smash"
            | "substack"
            | "text"
            | "textbf"
            | "textit"
            | "textmd"
            | "textnormal"
            | "textrm"
            | "textsc"
            | "textsf"
            | "textsl"
            | "texttt"
            | "textup"
            | "underbrace"
            | "bm"
            | "boldsymbol"
    )
}
