// Generates src/coding_agent/utils/oracle_data.rs from oracle_output.json + grid_args.json.
// Errors are encoded as "!ERR<message>"; "!SKIP" marks cwd-dependent node:path
// entries that cannot be pinned on an arbitrary machine; "!CWD" means the
// expected value equals the resolving process cwd.
import fs from "node:fs";
import path from "node:path";

const o = JSON.parse(fs.readFileSync(new URL("./oracle_output.json", import.meta.url), "utf8"));
const GRIDS = JSON.parse(fs.readFileSync(new URL("./grid_args.json", import.meta.url), "utf8"));
const CWD_WIN = "C:\\Users\\13063\\Desktop\\code\\agent work\\pi-rust\\scratch\\utils_oracle";
const CWD_POSIX = "/Users/13063/Desktop/code/agent work/pi-rust/scratch/utils_oracle";

function esc(s) {
  let out = "";
  for (const ch of String(s)) {
    const c = ch.codePointAt(0);
    if (ch === "\\") out += "\\\\";
    else if (ch === '"') out += '\\"';
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (c < 0x20 || c === 0x7f) out += `\\u{${c.toString(16)}}`;
    else out += ch;
  }
  return `"${out}"`;
}

const L = [];
const w = (s) => L.push(s);

w("// Generated by scratch/utils_oracle/gen_data.mjs from oracle_output.json — do not edit by hand.");
w("// Every value was captured by running the actual upstream TypeScript sources with node");
w("// (type stripping) plus the vendored npm deps (yaml 2.9.0, chalk 6.0.0, hosted-git-info");
w("// 9.0.3) extracted from the local npm cache.");
w("");
w("// ---------- strip_ansi ----------");
w(`pub const STRIP_ANSI_COMPAT: &[(&str, &str)] = &[`);
for (const { input, got } of o.strip_ansi_compat) w(`    (${esc(input)}, ${esc(got)}),`);
w(`];`);
w(`pub const STRIP_ANSI_TOOL_OUTPUT: &str = ${esc(o.strip_ansi_extra.tool_output)};`);
w(`pub const STRIP_ANSI_BOM_AND_COLOR: &str = ${esc(o.strip_ansi_extra.bom_and_color)};`);
w("");
w("// ---------- strip_json_comments ----------");
w(`pub const STRIP_JSON_COMMENTS: &[(&str, &str)] = &[`);
for (const { input, got } of o.strip_json_comments) w(`    (${esc(input)}, ${esc(got)}),`);
w(`];`);
w("");
w("// ---------- normalize_windows_shell_path ----------");
w(`pub const NORMALIZE_WINDOWS_SHELL_PATH: &[(&str, &str)] = &[`);
for (const { input, got } of o.normalize_windows_shell_path) w(`    (${esc(input)}, ${esc(got)}),`);
w(`];`);
w("");
w("// ---------- normalize_path ----------");
w('// Entries: (platform, input, options tag, expected). "!ERR" prefix = error message suffix.');
w('// Options tags: "" none, "trim", "unicode", "at", "home", "noexpand".');
w("// Posix entries for file:// inputs were manually corrected: the oracle host runs Windows,");
w("// so node:url fileURLToPath ignored the flipped process.platform. Substituted values follow");
w("// node's documented posix fileURLToPath algorithm.");
const posixFileUrlOverrides = new Map([
  ["file:///C:/dir/file.txt", "/C:/dir/file.txt"],
  ["file:///C:/dir/file%20with%20spaces.txt", "/C:/dir/file with spaces.txt"],
  ["file:///dir/file.txt", "/dir/file.txt"],
  ["file:///C:/bad/%E0%A4%A", "!ERRURIError: URI malformed"],
]);
// The tilde expansion uses `join` from "node:path", which is bound to the
// REAL platform (win32 on the oracle host) — capture-side artifact, same
// family as the fileURLToPath entries above. The posix flavor is corrected
// to node-on-posix join semantics (`<home>/<rest>`).
const posixJoinOverrides = new Map([
  ["~/file.txt", "C:\\Users\\oracle/file.txt"],
  ["~/proj", "C:\\home\\me/proj"],
]);
w(`pub const NORMALIZE_PATH: &[(&str, &str, &str, &str)] = &[`);
for (const platform of ["win32", "posix"]) {
  for (const r of o.normalize_path[platform]) {
    const tag =
      r.options === undefined ? "" :
      r.options.trim ? "trim" :
      r.options.normalizeUnicodeSpaces ? "unicode" :
      r.options.stripAtPrefix ? "at" :
      r.options.expandTilde === false ? "noexpand" :
      r.options.homeDir !== undefined ? `home=${r.options.homeDir}` : "";
    let expected = r.error !== undefined ? `!ERR${r.error}` : r.got;
    if (platform === "posix" && posixFileUrlOverrides.has(r.input)) {
      expected = posixFileUrlOverrides.get(r.input);
    }
    if (platform === "posix" && !expected.startsWith("!ERR") && posixJoinOverrides.has(r.input)) {
      expected = posixJoinOverrides.get(r.input);
    }
    w(`    (${esc(platform)}, ${esc(r.input)}, ${esc(tag)}, ${esc(expected)}),`);
  }
}
w(`];`);
w(`pub const NORMALIZE_PATH_HOME: &str = ${esc("C:\\Users\\oracle")};`);
w("");
w("// ---------- is_local_path ----------");
w(`pub const IS_LOCAL_PATH: &[(&str, bool)] = &[`);
for (const { input, got } of o.is_local_path) w(`    (${esc(input)}, ${got}),`);
w(`];`);
w("");
w("// ---------- resolve_path (captured on the win32 oracle host) ----------");
w(`pub const RESOLVE_PATH: &[(&str, &str, &str)] = &[`);
for (const r of o.resolve_path) {
  const expected = r.error !== undefined ? `!ERR${r.error}` : r.got;
  w(`    (${esc(r.input)}, ${esc(r.base)}, ${esc(expected)}),`);
}
w(`];`);
w(`pub const CWD_RELATIVE_PATH: &[(&str, &str, &str)] = &[`);
for (const r of o.cwd_relative_path) {
  const expected = r.error !== undefined ? `!ERR${r.error}` : (r.got === null ? "!NONE" : r.got);
  w(`    (${esc(r.fp)}, ${esc(r.cwd)}, ${esc(expected)}),`);
}
w(`];`);
w(`pub const FORMAT_PATH_RELATIVE: &[(&str, &str, &str)] = &[`);
for (const r of o.format_relative) {
  const expected = r.error !== undefined ? `!ERR${r.error}` : r.got;
  w(`    (${esc(r.fp)}, ${esc(r.cwd)}, ${esc(expected)}),`);
}
w(`];`);
w("");
w("// ---------- node:path grid ----------");
// cwd-dependent values are encoded so tests can substitute the live cwd:
// - a value embedding the captured cwd verbatim becomes "!CWD" + suffix;
// - any other cwd-derived value (e.g. after ".." pops, or a pure ".." chain)
//   becomes "!REL" + path.relative(capturedCwd, value), which the test
//   re-resolves against the live cwd with the same flavor.
import pathMod from "node:path";
// Replace the captured cwd prefix with "!CWD" (keeps any suffix such as the
// resolved tail of `path.resolve`). The win32 match is case-insensitive
// because node preserves the drive-letter case of the input.
const ciIndexOf = (haystack, needle) => {
  const h = haystack.toLowerCase();
  const n = needle.toLowerCase();
  return h.indexOf(n);
};
const substituteCwdPartial = (s) => {
  if (ciIndexOf(s, CWD_WIN) !== -1) {
    const i = ciIndexOf(s, CWD_WIN);
    return "!CWD" + s.slice(i + CWD_WIN.length);
  }
  if (ciIndexOf(s, CWD_POSIX) !== -1) {
    const i = ciIndexOf(s, CWD_POSIX);
    return "!CWD" + s.slice(i + CWD_POSIX.length);
  }
  return s;
};
const relEncode = (value, flavor) => {
  if (value.includes(CWD_WIN) || value.includes(CWD_POSIX)) {
    return substituteCwdPartial(value);
  }
  // Only absolute values are re-encoded relative to the captured cwd;
  // already-relative results (e.g. "..\\c" between two absolute inputs) are
  // cwd-independent and stay pinned.
  const absolute = /^[a-zA-Z]:[\\/]/.test(value) || value.startsWith("/") || value.startsWith("\\");
  if (!absolute) {
    return value;
  }
  const captured = flavor === "win32" ? CWD_WIN : CWD_POSIX;
  const rel = flavor === "win32"
    ? pathMod.win32.relative(captured, value)
    : pathMod.posix.relative(captured, value);
  return rel.startsWith("..") ? `!REL${rel}` : value;
};
const argList = (args) => `&[${args.map(esc).join(", ")}]`;

for (const flavor of ["win32", "posix"]) {
  const np = o.node_path[flavor];
  const f = flavor === "win32" ? "WIN32" : "POSIX";
  w(`pub const NODE_PATH_${f}_RESOLVE: &[(&[&str], &str)] = &[`);
  GRIDS.resolve.forEach((args, i) =>
    w(`    (${argList(args)}, ${esc(relEncode(np.resolve[i], flavor))}),`));
  w(`];`);
  w(`pub const NODE_PATH_${f}_IS_ABSOLUTE: &[(usize, bool)] = &[`);
  np.isAbsolute.forEach((v, i) => w(`    (${i}, ${v}),`));
  w(`];`);
  w(`pub const NODE_PATH_${f}_RELATIVE: &[(&str, &str, &str)] = &[`);
  GRIDS.relative.forEach(([from, to], i) => {
    const raw = np.relative[i];
    const deep = o.node_path_relative_deep[flavor][i];
    let encoded;
    if (raw === deep) {
      encoded = relEncode(raw, flavor);
    } else {
      // Depth-dependent: the ".."-chain has one link per cwd level; any
      // trailing non-".." segments are fixed suffix.
      const segments = raw.split(/[\\/]/);
      const rest = segments.filter((segment) => segment !== "..");
      const sep = flavor === "win32" ? "\\" : "/";
      encoded = `!DEPTH${rest.length > 0 ? sep + rest.join(sep) : ""}`;
    }
    w(`    (${esc(from)}, ${esc(to)}, ${esc(encoded)}),`);
  });
  w(`];`);
  w(`pub const NODE_PATH_${f}_JOIN: &[(&[&str], &str)] = &[`);
  GRIDS.join.forEach((args, i) => w(`    (${argList(args)}, ${esc(np.join[i])}),`));
  w(`];`);
  w(`pub const NODE_PATH_${f}_NORMALIZE: &[(&str, &str)] = &[`);
  GRIDS.normalize.forEach((p, i) => w(`    (${esc(p[0])}, ${esc(np.normalize[i])}),`));
  w(`];`);
  w("");
}
w("// ---------- frontmatter ----------");
w('// (input, frontmatter json or "!ERR...", body)');
w(`pub const FRONTMATTER: &[(&str, &str, &str)] = &[`);
for (const r of o.frontmatter) {
  const fm = r.error !== undefined ? `!ERR${r.error}` : JSON.stringify(r.frontmatter);
  w(`    (${esc(r.input)}, ${esc(fm)}, ${esc(r.body ?? "")}),`);
}
w(`];`);
w('// (input, stripped or "!ERR...")');
w(`pub const STRIP_FRONTMATTER: &[(&str, &str)] = &[`);
for (const r of o.strip_frontmatter) {
  const got = r.error !== undefined ? `!ERR${r.error}` : r.got;
  w(`    (${esc(r.input)}, ${esc(got)}),`);
}
w(`];`);
w("");
w("// ---------- parse_git_url ----------");
w('// (source, repo|host|path|ref|pinned or "null")');
w(`pub const PARSE_GIT_URL: &[(&str, &str)] = &[`);
for (const { source, got } of o.parse_git_url) {
  const enc = got === null ? "null" :
    [got.repo, got.host, got.path, got.ref ?? "", String(got.pinned)].join("|");
  w(`    (${esc(source)}, ${esc(enc)}),`);
}
w(`];`);
w('// (url, domain|user|project|committish or "null")');
w(`pub const HOSTED_FROM_URL: &[(&str, &str)] = &[`);
for (const { u, info } of o.hosted_from_url) {
  const enc = info === null ? "null" :
    [info.domain, info.user ?? "", info.project ?? "", info.committish ?? ""].join("|");
  w(`    (${esc(u)}, ${esc(enc)}),`);
}
w(`];`);
w("");
w("// ---------- detect_mime ----------");
w('// (case name, detected mime or "null")');
w(`pub const DETECT_MIME: &[(&str, &str)] = &[`);
for (const { name, got } of o.detect_mime) {
  w(`    (${esc(name)}, ${esc(got ?? "null")}),`);
}
w(`];`);
w("");
w("// ---------- exif transforms (mock photon) ----------");
w("// (orientation, out_width, out_height, pixels)");
w(`pub const EXIF_TRANSFORMS: &[(i32, u32, u32, &[u8])] = &[`);
for (const t of o.exif_transforms) {
  w(`    (${t.orientation}, ${t.out_width}, ${t.out_height}, &[${t.pixels.join(",")}]),`);
}
w(`];`);
w("");
w("// ---------- chalk yellow ----------");
w(`pub const CHALK_YELLOW: [&str; 4] = [${[0, 1, 2, 3].map((l) => esc(o.chalk_yellow[l])).join(", ")}];`);

const OUT = process.argv[2];
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, L.join("\n") + "\n");
console.log("wrote", OUT, L.length, "lines");
