// Generates Rust constant blocks from oracle_output.json for pasting into
// src/tui/tui_tests.rs. Byte arrays use Rust string escaping; structured
// values are canonical JSON (recursively key-sorted) so the Rust side can
// rebuild the same shape with serde_json and compare byte-for-byte.
import fs from "node:fs";

const o = JSON.parse(fs.readFileSync(new URL("./oracle_output.json", import.meta.url), "utf8"));

function esc(s) {
	let out = "";
	for (const ch of String(s)) {
		const c = ch.codePointAt(0);
		if (ch === "\\") out += "\\\\";
		else if (ch === '"') out += '\\"';
		else if (ch === "\n") out += "\\n";
		else if (ch === "\r") out += "\\r";
		else if (ch === "\t") out += "\\t";
		else if (c < 0x20 || c === 0x7f) out += `\\u{${c.toString(16)}}`;
		else out += ch;
	}
	return `"${out}"`;
}

function canonical(v) {
	if (Array.isArray(v)) return v.map(canonical);
	if (v && typeof v === "object") {
		const sorted = {};
		for (const k of Object.keys(v).sort()) sorted[k] = canonical(v[k]);
		return sorted;
	}
	return v;
}
const json = (v) => JSON.stringify(canonical(v));

const L = [];
const w = (s) => L.push(s);
const writes = (name, arr) => {
	w(`pub const ${name}: &[&str] = &[${arr.map(esc).join(", ")}];`);
};
const jstr = (name, v) => {
	w(`pub const ${name}: &str = ${esc(json(v))};`);
};
const num = (name, v) => {
	w(`pub const ${name}: usize = ${v};`);
};

w("// Generated by scratch/tui_oracle/gen_data.mjs from oracle_output.json — do not edit by hand.");
w("// Every value was captured by running the actual upstream tui.ts (TuiBase) and the");
w("// referenced upstream modules under node --experimental-strip-types; byte arrays are");
w("// FakeTerminal write boundaries (one entry per terminal.write call).");
w("");

// lifecycle
writes("LIFECYCLE_WRITES", o.lifecycle.writes);
num("LIFECYCLE_FULL_REDRAWS", o.lifecycle.fullRedraws);
writes("LIFECYCLE_STOP_WRITES", o.lifecycle_stop.writes);
writes("SCHEME_NOTIF_BEFORE_START_WRITES", o.scheme_notifications_before_start.writes);
writes("SCHEME_NOTIF_START_WRITES", o.scheme_notifications_start.writes);
writes("SCHEME_NOTIF_DISABLE_WRITES", o.scheme_notifications_disable.writes);
writes("SCHEME_NOTIF_STOP_WRITES", o.scheme_notifications_stop.writes);

jstr("KEYBOARD_PREEMPT", o.keyboard_preempt);
writes("THROTTLED_BEFORE_WRITES", o.throttled_frame.before_timer.writes);
num("THROTTLED_BEFORE_RC", o.throttled_frame.before_timer.renderCount);
writes("THROTTLED_AFTER_WRITES", o.throttled_frame.after_timer.writes);
num("THROTTLED_AFTER_RC", o.throttled_frame.after_timer.renderCount);

jstr("DEBUG_KEY", o.debug_key);
jstr("INPUT_PIPELINE", o.input_pipeline);
jstr("KEY_RELEASE", o.key_release);

writes("CELL_SIZE_START_WRITES", o.cell_size_start.writes);
jstr("CELL_SIZE_RESPONSE", o.cell_size_response);
jstr("CELL_SIZE_AFTER", o.cell_size_after);
writes("CELL_SIZE_DISABLED_START_WRITES", o.cell_size_disabled_start.writes);
jstr("CELL_SIZE_DISABLED_ESCAPE", o.cell_size_disabled_escape);

writes("OSC11_QUERY_WRITES", o.osc11_query_writes);
jstr("OSC11_RESPONSE", o.osc11_response);
jstr("OSC11_TIMEOUT", o.osc11_timeout);
writes("SCHEME_QUERY_WRITES", o.scheme_query_writes);
jstr("SCHEME_REPORT", o.scheme_report);
jstr("SCHEME_TIMEOUT", o.scheme_timeout);

writes("SHRINK_INITIAL_WRITES", o.shrink_clear.initial_writes);
writes("SHRINK_WRITES", o.shrink_clear.shrink_writes);
jstr("SHRINK_CLEAR", {
	delta: o.shrink_clear.full_redraw_delta,
	viewport: o.shrink_clear.viewport,
});
jstr("SHRINK_MORE", o.shrink_more);

o.spinner.frames.forEach((frame, i) => writes(`SPINNER_FRAME_${i}`, frame));
jstr("SPINNER_VIEWPORT", o.spinner.viewport);

writes("DELETED_GROWN_WRITES", o.deleted_viewport_up.grown_writes);
writes("DELETED_SHRINK_WRITES", o.deleted_viewport_up.shrink_writes);
jstr("DELETED_VIEWPORT_UP", {
	delta: o.deleted_viewport_up.full_redraw_delta,
	viewport: o.deleted_viewport_up.viewport,
});
writes("APPEND_WRITES", o.append_after_shrink.writes);
jstr("APPEND_AFTER_SHRINK", {
	delta: o.append_after_shrink.full_redraw_delta,
	viewport: o.append_after_shrink.viewport,
});

writes("TRANSIENT_WRITES", o.transient_inflation.writes);
jstr("TRANSIENT_INFLATION", {
	delta: o.transient_inflation.full_redraw_delta,
	viewport: o.transient_inflation.viewport,
});

writes("RESIZE_WIDTH_WRITES", o.resize.width_change.writes);
writes("RESIZE_HEIGHT_WRITES", o.resize.height_change.writes);
jstr("RESIZE_DELTAS", {
	width: o.resize.width_change.delta,
	height: o.resize.height_change.delta,
});

for (const c of o.overlay_options) {
	const constName = c.name.toUpperCase();
	jstr(`OVLOPT_${constName}_VIEWPORT`, c.viewport);
	w(
		`pub const OVLOPT_${constName}_WIDTH: &str = ${
			c.requestedWidth === undefined || c.requestedWidth === null ? `"null"` : `"${c.requestedWidth}"`
		};`,
	);
}
jstr("OVERLAY_STACK", o.overlay_stack);
writes("STYLE_LEAK_NO_OVERLAY_LINES", o.style_leak.no_overlay_lines);
writes("STYLE_LEAK_OVERLAY_LINES", o.style_leak.overlay_lines);
writes("COMPOSITE_TABLE", o.composite_table);

writes("CURSOR_MARKER_WRITES", o.cursor_marker.writes);
writes("CURSOR_MARKER_MOVED_WRITES", o.cursor_marker_moved.writes);
writes("CURSOR_MARKER_DISABLED_WRITES", o.cursor_marker_disabled.writes);
jstr("CURSOR_MARKER_VIEWPORT", o.cursor_marker.viewport);
jstr("MOUSE_OVERLAY_HIT", o.mouse_overlay_hit);

w("");
for (const [key, value] of Object.entries(o.focus_suite)) {
	const constName = `FOCUS_${key.toUpperCase()}`;
	jstr(constName, value);
}

fs.writeFileSync(new URL("./expected_consts.rs", import.meta.url), L.join("\n") + "\n");
console.log("emitted", L.length, "lines");
